In [10]:
import pandas as pd
import requests
import xml.etree.ElementTree as ET
import time
import re

# 1. Load the initial dataset and extract the names
print("Loading initial dataset...")
df = pd.read_csv('../q/test_scrape.csv')
games_list = df['game'].tolist()

new_dataset = []
print(f"Starting extraction for {len(games_list)} games...\n")

# 2. Define headers to mimic a web browser (Bypasses 401 Unauthorized errors)
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
}

# 3. Loop through each game
for original_name in games_list:
    # CLEANING: Remove Wikipedia tags like " (role-playing game)"
    search_name = re.sub(r' \(.*?\)', '', str(original_name)).strip()
    print(f"Processing: {search_name}...")
    
    try:
        # --- PHASE 1: Search API (Get the ID) ---
        # We use boardgamegeek.com instead of rpggeek.com to avoid Cloudflare blocks. 
        # The parameter type=rpgitem ensures we only search for RPGs.
        search_url = "https://boardgamegeek.com/xmlapi2/search"
        search_params = {"query": search_name, "type": "rpgitem", "exact": 1}
        
        search_res = requests.get(search_url, params=search_params, headers=headers)
        time.sleep(2) # MANDATORY sleep to avoid IP bans (429 Too Many Requests)
        
        if search_res.status_code == 200:
            root = ET.fromstring(search_res.content)
            item = root.find('item')
            
            if item is not None:
                game_id = item.get('id')
                
                # --- PHASE 2: Thing API (Get the Stats and Details) ---
                thing_url = "https://boardgamegeek.com/xmlapi2/thing"
                thing_params = {"id": game_id, "stats": 1}
                
                thing_res = requests.get(thing_url, params=thing_params, headers=headers)
                time.sleep(2) # MANDATORY sleep
                
                if thing_res.status_code == 200:
                    t_root = ET.fromstring(thing_res.content)
                    t_item = t_root.find('item')
                    
                    if t_item is not None:
                        # Extract Description
                        desc_tag = t_item.find('description')
                        description = desc_tag.text if desc_tag is not None else "No description"
                        
                        # Extract Average Score
                        average_score = None
                        avg_tag = t_item.find('.//statistics/ratings/average')
                        if avg_tag is not None:
                            average_score = avg_tag.get('value')
                            
                        # Extract Number of Reviews/Ratings
                        num_ratings = None
                        ratings_tag = t_item.find('.//statistics/ratings/usersrated')
                        if ratings_tag is not None:
                            num_ratings = ratings_tag.get('value')
                            
                        # Save the successfully scraped data
                        new_dataset.append({
                            'Name': search_name,
                            'Description': description,
                            'Average Score': average_score,
                            'Number of Reviews': num_ratings
                        })
                        print(f"  -> Success! Score: {average_score} | Reviews: {num_ratings}")
                        continue 
                    else:
                        print("  -> Game details not found in Thing API.")
                else:
                    print(f"  -> Thing API failed. Status Code: {thing_res.status_code}")
            else:
                print("  -> Game not found in Search API results.")
        else:
            print(f"  -> Search API failed. Status Code: {search_res.status_code}")
            
        # If any step above fails normally (e.g. not found), append empty values so we don't lose the row
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})
            
    except Exception as e:
        print(f"  -> Error processing {search_name}: {e}")
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})

Loading initial dataset...
Starting extraction for 775 games...

Processing: 13th Age...
  -> Search API failed. Status Code: 401
Processing: The 23rd Letter...
  -> Search API failed. Status Code: 401
Processing: 2300 AD...

KeyboardInterrupt:

In [ ]:
# 4. Save to a new CSV file
new_df = pd.DataFrame(new_dataset)
new_df.to_csv('ttrpg_api_dataset.csv', index=False)
print("\nExtraction Complete! Data saved to 'ttrpg_api_dataset.csv'")

In [13]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import json
import time

print("Loading initial dataset...")
try:
    df = pd.read_csv('test_scrape.csv')
    games_list = df['game'].tolist()
except FileNotFoundError:
    df = pd.read_csv('../q/test_scrape.csv')
    games_list = df['game'].tolist()

new_dataset = []
print(f"Starting Web Scrape for {len(games_list)} games...\n")

# Headers are critical for scraping to avoid being blocked as a bot
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
}

for original_name in games_list:
    # CLEANING: Remove Wikipedia tags
    search_name = re.sub(r' \(.*?\)', '', str(original_name)).strip()
    print(f"Scraping: {search_name}...")
    
    try:
        # --- PHASE 1: Scrape the Search Page to get the Game's URL ---
        # We use the standard web search URL, not the API
        search_url = "https://boardgamegeek.com/geeksearch.php"
        search_params = {"action": "search", "objecttype": "rpgitem", "q": search_name}
        
        search_res = requests.get(search_url, params=search_params, headers=headers)
        time.sleep(2) # Respect the server
        
        if search_res.status_code == 200:
            soup = BeautifulSoup(search_res.content, 'html.parser')
            
            # Find the first link in the search results that points to an RPG item
            link_tag = soup.find('a', href=re.compile(r'^/rpgitem/'))
            
            if link_tag:
                # Construct the full URL to the game's actual webpage
                item_url = "https://boardgamegeek.com" + link_tag['href']
                
                # --- PHASE 2: Scrape the Game's Webpage ---
                item_res = requests.get(item_url, headers=headers)
                time.sleep(5) 
                
                if item_res.status_code == 200:
                    item_soup = BeautifulSoup(item_res.content, 'html.parser')
                    
                    # 1. Extract Description from the SEO Meta Tags (Easiest HTML scraping)
                    meta_desc = item_soup.find('meta', attrs={'name': 'description'})
                    description = meta_desc['content'] if meta_desc else "No description"
                    
                    # 2. Extract Stats using BeautifulSoup + RegEx!
                    # BGG hides the score in a Javascript variable called GEEK.geekitemPreload
                    average_score = None
                    num_ratings = None
                    
                    # Find all script tags on the page
                    scripts = item_soup.find_all('script')
                    for script in scripts:
                        if script.string and 'GEEK.geekitemPreload' in script.string:
                            # Use RegEx to extract the JSON dictionary hidden inside the Javascript text
                            json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                            
                            if json_match:
                                # Convert the extracted string into a Python dictionary
                                hidden_data = json.loads(json_match.group(1))
                                
                                # Navigate the dictionary to find the stats
                                stats = hidden_data.get('item', {}).get('stats', {})
                                average_score = stats.get('average')
                                num_ratings = stats.get('usersrated')
                            break # We found the data, stop checking other scripts
                            
                    # Save the scraped row
                    new_dataset.append({
                        'Name': search_name,
                        'Description': description,
                        'Average Score': average_score,
                        'Number of Reviews': num_ratings
                    })
                    print(f"  -> Scrape Success! Score: {average_score} | Reviews: {num_ratings}")
                    continue
                else:
                    print(f"  -> Failed to load item page. Status: {item_res.status_code}")
            else:
                print("  -> Game not found in search results.")
        else:
            print(f"  -> Search page failed. Status: {search_res.status_code}")
            
        # Append empty row if failed
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})
            
    except Exception as e:
        print(f"  -> Error scraping {search_name}: {e}")
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})

Loading initial dataset...
Starting Web Scrape for 775 games...

Scraping: 13th Age...
  -> Failed to load item page. Status: 403
Scraping: The 23rd Letter...

KeyboardInterrupt:

In [ ]:
# Save to CSV
new_df = pd.DataFrame(new_dataset)
new_df.to_csv('ttrpg_scraped_dataset.csv', index=False)
print("\nWeb Scrape Complete! Data saved to 'ttrpg_scraped_dataset.csv'")

In [14]:
!pip install cloudscraper

Collecting cloudscraper
  Using cached cloudscraper-1.2.71-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\admin\anaconda3\lib\site-packages (from cloudscraper) (3.0.9)
Requirement already satisfied: requests>=2.9.2 in c:\users\admin\anaconda3\lib\site-packages (from cloudscraper) (2.32.2)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\admin\anaconda3\lib\site-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.9.2->cloudscraper) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.9.2->cloudscraper) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.9.2->cloudscraper) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.9.2->cloudscraper) (2026.1.4)
Using cached cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
Installing collected packages: cloudscraper
Successfully installed cloudscraper-1.2.71

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import re
import json
import time
import cloudscraper # NEW LIBRARY

print("Loading initial dataset...")
try:
    df = pd.read_csv('test_scrape.csv')
    games_list = df['game'].tolist()
except FileNotFoundError:
    df = pd.read_csv('../q/test_scrape.csv')
    games_list = df['game'].tolist()

new_dataset = []
print(f"Starting Web Scrape for {len(games_list)} games...\n")

# 🌟 THE FIX: Create a CloudScraper instance to bypass the 403 Forbidden block
# This perfectly mimics a desktop Chrome browser's fingerprint
scraper = cloudscraper.create_scraper(
    browser={
        'browser': 'chrome',
        'platform': 'windows',
        'desktop': True
    }
)

for original_name in games_list:
    search_name = re.sub(r' \(.*?\)', '', str(original_name)).strip()
    print(f"Scraping: {search_name}...")
    
    try:
        # --- PHASE 1: Scrape Search Page ---
        search_url = "https://boardgamegeek.com/geeksearch.php"
        search_params = {"action": "search", "objecttype": "rpgitem", "q": search_name}
        
        # Use scraper.get instead of requests.get
        search_res = scraper.get(search_url, params=search_params)
        time.sleep(3) # Be polite to the server
        
        if search_res.status_code == 200:
            soup = BeautifulSoup(search_res.content, 'html.parser')
            link_tag = soup.find('a', href=re.compile(r'^/rpgitem/'))
            
            if link_tag:
                item_url = "https://boardgamegeek.com" + link_tag['href']
                
                # --- PHASE 2: Scrape Game Page ---
                item_res = scraper.get(item_url)
                time.sleep(3) 
                
                if item_res.status_code == 200:
                    item_soup = BeautifulSoup(item_res.content, 'html.parser')
                    
                    # 1. Extract Description
                    meta_desc = item_soup.find('meta', attrs={'name': 'description'})
                    description = meta_desc['content'] if meta_desc else "No description"
                    
                    # 2. Extract Stats from JSON inside script
                    average_score = None
                    num_ratings = None
                    
                    scripts = item_soup.find_all('script')
                    for script in scripts:
                        if script.string and 'GEEK.geekitemPreload' in script.string:
                            json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                            if json_match:
                                hidden_data = json.loads(json_match.group(1))
                                stats = hidden_data.get('item', {}).get('stats', {})
                                average_score = stats.get('average')
                                num_ratings = stats.get('usersrated')
                            break 
                            
                    new_dataset.append({
                        'Name': search_name,
                        'Description': description,
                        'Average Score': average_score,
                        'Number of Reviews': num_ratings
                    })
                    print(f"  -> Scrape Success! Score: {average_score} | Reviews: {num_ratings}")
                    continue
                else:
                    print(f"  -> Failed to load item page. Status: {item_res.status_code}")
            else:
                print("  -> Game not found in search results.")
        else:
            print(f"  -> Search page failed. Status: {search_res.status_code}")
            
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})
            
    except Exception as e:
        print(f"  -> Error scraping {search_name}: {e}")
        new_dataset.append({'Name': search_name, 'Description': None, 'Average Score': None, 'Number of Reviews': None})

new_df = pd.DataFrame(new_dataset)
new_df.to_csv('ttrpg_scraped_dataset.csv', index=False)
print("\nWeb Scrape Complete! Data saved to 'ttrpg_scraped_dataset.csv'")

Loading initial dataset...
Starting Web Scrape for 775 games...

Scraping: 13th Age...
  -> Scrape Success! Score: 7.90114 | Reviews: 131
Scraping: The 23rd Letter...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: 2300 AD...
  -> Scrape Success! Score: 7.28917 | Reviews: 60
Scraping: 3D&T...
  -> Scrape Success! Score: 7 | Reviews: 1
Scraping: 7th Sea...
  -> Scrape Success! Score: 7.57759 | Reviews: 116
Scraping: Aberrant...
  -> Scrape Success! Score: 6.96875 | Reviews: 72
Scraping: ACE Agents!...
  -> Scrape Success! Score: 6 | Reviews: 1
Scraping: Active Exploits...
  -> Scrape Success! Score: 5.85 | Reviews: 10
Scraping: Editions of Dungeons & Dragons...
  -> Scrape Success! Score: 6.66667 | Reviews: 3
Scraping: Advanced Fighting Fantasy...
  -> Scrape Success! Score: 7.73913 | Reviews: 23
Scraping: Adventure!...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Adventure!...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Adventurers Guild...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Adventures in Fantasy...
  -> Scrape Success! Score: 4.5 | Reviews: 2
Scraping: The Adventures of Indiana Jones Role-Playing Game...
  -> Scrape Success! Score: 5.38333 | Reviews: 27
Scraping: Adventures in Middle-earth...
  -> Scrape Success! Score: 7.90714 | Reviews: 42
Scraping: After the Bomb...
  -> Scrape Success! Score: 6.46667 | Reviews: 45
Scraping: Aftermath!...
  -> Scrape Success! Score: 6.80556 | Reviews: 36
Scraping: Afterwars...
  -> Scrape Success! Score: 8 | Reviews: 1
Scraping: Age of the Tempest...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Age of Ruin...
  -> Scrape Success! Score: 5 | Reviews: 1
Scraping: Agone...
  -> Scrape Success! Score: 7.02941 | Reviews: 17
Scraping: Albedo...
  -> Scrape Success! Score: 6.6 | Reviews: 5
Scraping: Alice is Missing...
  -> Scrape Success! Score: 7.63821 | Reviews: 280
Scraping: ALIEN: The Roleplaying Game...
  -> Scrape Success! Score: 8.24778 | Reviews: 135
Scraping: Aliens Adventure Game...
  -> Scrape Success! Score: 6.48387 | Reviews: 31
Scraping: All Flesh Must Be Eaten...
  -> Scrape Success! Score: 7.04823 | Reviews: 141
Scraping: All-Star Wrestling...
  -> Scrape Success! Score: 9 | Reviews: 1
Scraping: Alma Mater...
  -> Scrape Success! Score: 7.125 | Reviews: 8
Scraping: Alshard...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Alshard...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Alternity...
  -> Scrape Success! Score: 7.02113 | Reviews: 71
Scraping: Amazing Engine...
  -> Scrape Success! Score: 5.69231 | Reviews: 13
Scraping: Amber Diceless Roleplaying...
  -> Game not found in search results.
Scraping: Anima: Beyond Fantasy...
  -> Scrape Success! Score: 6.86512 | Reviews: 43
Scraping: Angel...
  -> Scrape Success! Score: 7.31579 | Reviews: 38
Scraping: Apocalypse Keys...
  -> Scrape Success! Score: 7.25 | Reviews: 4
Scraping: Apocalypse World...
  -> Scrape Success! Score: 8.07522 | Reviews: 222
Scraping: Arcana Unearthed...
  -> Scrape Success! Score: 6.86429 | Reviews: 35
Scraping: Archaeron...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Arduin...
  -> Scrape Success! Score: 8.83333 | Reviews: 6
Scraping: Aria...
  -> Scrape Success! Score: 4.52941 | Reviews: 17
Scraping: Arianrhod RPG...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Armageddon: 2089...
  -> Scrape Success! Score: 3.5 | Reviews: 2
Scraping: Armageddon: The End Times...
  -> Scrape Success! Score: 7.23333 | Reviews: 15
Scraping: Armored Trooper VOTOMS: The Roleplaying Game...
  -> Game not found in search results.
Scraping: Army of Darkness Roleplaying Game...
  -> Scrape Success! Score: 7.128 | Reviews: 25
Scraping: Ars Magica...
  -> Scrape Success! Score: 7.91654 | Reviews: 133
Scraping: Artesia: Adventures in the Known World...
  -> Scrape Success! Score: 7.36111 | Reviews: 36
Scraping: Ashen Stars...
  -> Scrape Success! Score: 7.60213 | Reviews: 47
Scraping: Atlantis...
  -> Scrape Success! Score: 7 | Reviews: 6
Scraping: Atomic Robo...
  -> Scrape Success! Score: 8.3617 | Reviews: 47
Scraping: Attack of the Humans...
  -> Scrape Success! Score: 5.5 | Reviews: 2
Scraping: The Authority Role-Playing Game...
  -> Scrape Success! Score: 6.94444 | Reviews: 9
Scraping: Avatar Legends: The Roleplaying Game...
  -> Scrape Success! Score: 6.53704 | Reviews: 27
Scraping: Babylon 5...
  -> Scrape Success! Score: 6.42857 | Reviews: 14
Scraping: Badlands...
  -> Scrape Success! Score: 6.5 | Reviews: 2
Scraping: BASH!...
  -> Scrape Success! Score: 8.125 | Reviews: 8
Scraping: Barony...
  -> Scrape Success! Score: 7.58333 | Reviews: 42
Scraping: Basic Fantasy RPG...
  -> Scrape Success! Score: 7.56452 | Reviews: 31
Scraping: Basic Role-Playing...
  -> Scrape Success! Score: 6.1 | Reviews: 10
Scraping: Batman Role-Playing Game...
  -> Scrape Success! Score: 6.36957 | Reviews: 23
Scraping: BattleDragons...
  -> Scrape Success! Score: 7 | Reviews: 1
Scraping: Battlelords of the 23rd Century...
  -> Scrape Success! Score: 8 | Reviews: 2
Scraping: Battlestar Galactica Role Playing Game...
  -> Scrape Success! Score: 6.69828 | Reviews: 29
Scraping: Behind Enemy Lines...
  -> Scrape Success! Score: 6.22222 | Reviews: 9
Scraping: Beyond the Supernatural...
  -> Scrape Success! Score: 6 | Reviews: 26
Scraping: Bifrost...
  -> Scrape Success! Score: 9 | Reviews: 1
Scraping: Big Bang Comics RPG...
  -> Game not found in search results.
Scraping: Big Eyes, Small Mouth...
  -> Scrape Success! Score: 3 | Reviews: 1
Scraping: Black Crusade...
  -> Scrape Success! Score: 7.58696 | Reviews: 46
Scraping: The Black Sword Hack...
  -> Scrape Success! Score: 7.8125 | Reviews: 8
Scraping: Blades in the Dark...
  -> Scrape Success! Score: 8.2581 | Reviews: 216
Scraping: Blade Runner: The Roleplaying Game...
  -> Scrape Success! Score: 8.1129 | Reviews: 31
Scraping: Blood Dawn...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Blood of Heroes...
  -> Scrape Success! Score: 6.27273 | Reviews: 11
Scraping: Blue Planet...
  -> Scrape Success! Score: 7.45833 | Reviews: 24
Scraping: Blue Rose...
  -> Scrape Success! Score: 7.05 | Reviews: 10
Scraping: Bluebeard's Bride...
  -> Scrape Success! Score: 7.32353 | Reviews: 17
Scraping: Boot Hill...
  -> Scrape Success! Score: 6.875 | Reviews: 44
Scraping: Brave New World...
  -> Scrape Success! Score: 5.85 | Reviews: 20
Scraping: Breaking the Ice...
  -> Scrape Success! Score: 7.45833 | Reviews: 24
Scraping: Brindlewood Bay...
  -> Scrape Success! Score: 8.88461 | Reviews: 26
Scraping: Bubblegum Crisis...
  -> Scrape Success! Score: 6.36364 | Reviews: 22
Scraping: Buccaneer...
  -> Scrape Success! Score: 7.33333 | Reviews: 3
Scraping: Buck Rogers XXVC...
  -> Scrape Success! Score: 7.61765 | Reviews: 17
Scraping: Buffy the Vampire Slayer Roleplaying Game...
  -> Scrape Success! Score: 6.96267 | Reviews: 75
Scraping: Bullwinkle and Rocky Role-Playing Party Game...
  -> Scrape Success! Score: 6.16667 | Reviews: 6
Scraping: Bunnies and Burrows...
  -> Scrape Success! Score: 7.05769 | Reviews: 26
Scraping: Bureau 13: Stalking the Night Fantastic...
  -> Scrape Success! Score: 6.90909 | Reviews: 11
Scraping: Roll20...
  -> Scrape Success! Score: 7.08824 | Reviews: 17
Scraping: Burning Empires...
  -> Scrape Success! Score: 7.46739 | Reviews: 92
Scraping: The Burning Wheel...
  -> Scrape Success! Score: 7.69891 | Reviews: 184
Scraping: Bushido...
  -> Scrape Success! Score: 7.58718 | Reviews: 39
Scraping: By the Gods...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Cadillacs and Dinosaurs...
  -> Scrape Success! Score: 6.94615 | Reviews: 13
Scraping: Cadwallon...
  -> Scrape Success! Score: 6.2 | Reviews: 5
Scraping: Call of Cthulhu...
  -> Scrape Success! Score: 8.29132 | Reviews: 524
Scraping: Capes...
  -> Scrape Success! Score: 6.80769 | Reviews: 13
Scraping: Cartoon Action Hour...
  -> Scrape Success! Score: 6.46 | Reviews: 10
Scraping: Car Wars...
  -> Scrape Success! Score: 8 | Reviews: 1
Scraping: Cassiopean Empire...
  -> Game not found in search results.
Scraping: Castles & Crusades...
  -> Scrape Success! Score: 7.69267 | Reviews: 75
Scraping: Castle Falkenstein...
  -> Scrape Success! Score: 7.95039 | Reviews: 129
Scraping: The Castle Perilous...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Challengers...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Champions...
  -> Scrape Success! Score: 7.22464 | Reviews: 69
Scraping: Changeling: The Dreaming...
  -> Scrape Success! Score: 7.11294 | Reviews: 85
Scraping: Changeling: The Lost...
  -> Scrape Success! Score: 7.66971 | Reviews: 104
Scraping: Children of the Sun...
  -> Scrape Success! Score: 4.5 | Reviews: 3
Scraping: Chill...
  -> Scrape Success! Score: 6.52857 | Reviews: 35
Scraping: Chivalry & Sorcery...
  -> Scrape Success! Score: 7 | Reviews: 21
Scraping: Chronicles of Ramlar...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: City of Mist...
  -> Scrape Success! Score: 7 | Reviews: 16
Scraping: Commando...
  -> Scrape Success! Score: 4 | Reviews: 3
Scraping: Companions' Tale...
  -> Scrape Success! Score: 9 | Reviews: 5
Scraping: Conan Role-Playing Game...
  -> Scrape Success! Score: 6.67391 | Reviews: 23
Scraping: Conan: Adventures in an Age Undreamed Of...
  -> Scrape Success! Score: 7.89762 | Reviews: 42
Scraping: GURPS Conan...
  -> Scrape Success! Score: 6.83333 | Reviews: 21
Scraping: Conan: The Roleplaying Game...
  -> Scrape Success! Score: 7.01351 | Reviews: 37
Scraping: The Confederate Rangers...
  -> Game not found in search results.
Scraping: Conspiracy X...
  -> Scrape Success! Score: 6.75758 | Reviews: 33
Scraping: Continuum...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Core Command...
  -> Scrape Success! Score: 5.07143 | Reviews: 7
Scraping: Corporation...
  -> Scrape Success! Score: 6.30769 | Reviews: 13
Scraping: CORPS...
  -> Scrape Success! Score: 8.16667 | Reviews: 6
Scraping: Coyote & Crow...
  -> Scrape Success! Score: 6.8 | Reviews: 5
Scraping: Creeks and Crawdads...
  -> Scrape Success! Score: 8.65 | Reviews: 2
Scraping: Crime Fighter...
  -> Scrape Success! Score: 7.75 | Reviews: 4
Scraping: Crimefighters...
  -> Game not found in search results.
Scraping: Crystalicum...
  -> Scrape Success! Score: 5.2 | Reviews: 5
Scraping: CthulhuTech...
  -> Scrape Success! Score: 7.0609 | Reviews: 78
Scraping: Cutthroat: The Shadow Wars...
  -> Game not found in search results.
Scraping: Cybergeneration...
  -> Scrape Success! Score: 7.42857 | Reviews: 14
Scraping: Cyberpunk 2013...
  -> Scrape Success! Score: 6.88571 | Reviews: 35
Scraping: Cyberpunk 2020...
  -> Scrape Success! Score: 7.52848 | Reviews: 223
Scraping: Cyberpunk RED...
  -> Scrape Success! Score: 7.67647 | Reviews: 34
Scraping: Cyberspace...
  -> Scrape Success! Score: 5.97619 | Reviews: 21
Scraping: Cyborg Commando...
  -> Scrape Success! Score: 3.51562 | Reviews: 16
Scraping: D6 Adventure...
  -> Scrape Success! Score: 7.08824 | Reviews: 17
Scraping: D6 Fantasy...
  -> Scrape Success! Score: 6.34211 | Reviews: 19
Scraping: D6 Space...
  -> Scrape Success! Score: 6.5 | Reviews: 2
Scraping: D6 System...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: D20 Future...
  -> Scrape Success! Score: 6.85167 | Reviews: 30
Scraping: D20 Modern...
  -> Scrape Success! Score: 6.48102 | Reviews: 108
Scraping: D20 Past...
  -> Scrape Success! Score: 6.23529 | Reviews: 17
Scraping: D20 System...
  -> Scrape Success! Score: 6.5 | Reviews: 2
Scraping: Dallas...
  -> Scrape Success! Score: 5.25 | Reviews: 8
Scraping: Danger International...
  -> Scrape Success! Score: 6.93333 | Reviews: 15
Scraping: Dangerous Journeys...
  -> Scrape Success! Score: 5.24 | Reviews: 25
Scraping: Daredevils...
  -> Scrape Success! Score: 6.77857 | Reviews: 21
Scraping: Dark Ages...
  -> Scrape Success! Score: 7.83333 | Reviews: 33
Scraping: Dark Champions...
  -> Scrape Success! Score: 8.09091 | Reviews: 11
Scraping: Dark Conspiracy...
  -> Scrape Success! Score: 6.88125 | Reviews: 40
Scraping: Dark Dungeons...
  -> Scrape Success! Score: 6.10526 | Reviews: 19
Scraping: The Dark Eye...
  -> Scrape Success! Score: 5.9 | Reviews: 10
Scraping: Dark Heresy...
  -> Scrape Success! Score: 7.48608 | Reviews: 273
Scraping: Dark Streets...
  -> Scrape Success! Score: 8 | Reviews: 2
Scraping: Darwin's World...
  -> Scrape Success! Score: 5.66667 | Reviews: 3
Scraping: Dawning Star...
  -> Scrape Success! Score: 7.33333 | Reviews: 3
Scraping: DC Adventures...
  -> Scrape Success! Score: 7.90645 | Reviews: 62
Scraping: DC Heroes...
  -> Scrape Success! Score: 7.22581 | Reviews: 31
Scraping: DC Universe Roleplaying Game...
  -> Scrape Success! Score: 6.44783 | Reviews: 23
Scraping: De Profundis...
  -> Scrape Success! Score: 6.93182 | Reviews: 22
Scraping: Dead Friend: A Game of Necromancy...
  -> Scrape Success! Score: 8 | Reviews: 1
Scraping: Dead Inside...
  -> Scrape Success! Score: 5.16667 | Reviews: 3
Scraping: Dead Reign...
  -> Scrape Success! Score: 6.91429 | Reviews: 7
Scraping: Deadlands: Hell on Earth...
  -> Scrape Success! Score: 7.07429 | Reviews: 35
Scraping: Deadlands: Lost Colony...
  -> Scrape Success! Score: 9 | Reviews: 1
Scraping: Deadlands...
  -> Scrape Success! Score: 8.0955 | Reviews: 111
Scraping: Deathwatch...
  -> Scrape Success! Score: 7.63211 | Reviews: 109
Scraping: Deliria...
  -> Scrape Success! Score: 6.55 | Reviews: 6
Scraping: Delta Force: America Strikes Back!...
  -> Game not found in search results.
Scraping: Delta Green...
  -> Scrape Success! Score: 8.56642 | Reviews: 271
Scraping: Degenesis...
  -> Scrape Success! Score: 7.98889 | Reviews: 27
Scraping: Demon City Shinjuku Role-Playing Game...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Demon Hunters Role Playing Game...
  -> Scrape Success! Score: 8 | Reviews: 4
Scraping: Demon: The Fallen...
  -> Scrape Success! Score: 7.1122 | Reviews: 41
Scraping: Deryni Adventure Game...
  -> Scrape Success! Score: 7.5 | Reviews: 4
Scraping: Dialect...
  -> Scrape Success! Score: 8.22727 | Reviews: 22
Scraping: Diana: Warrior Princess...
  -> Scrape Success! Score: 6.38889 | Reviews: 9
Scraping: Diaspora...
  -> Scrape Success! Score: 7.81828 | Reviews: 186
Scraping: Die...
  -> Scrape Success! Score: 5.54348 | Reviews: 23
Scraping: Dinky Dungeons...
  -> Scrape Success! Score: 6.25 | Reviews: 6
Scraping: Dinosaur Planet: Broncosaurus Rex...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Diomin...
  -> Scrape Success! Score: 3.5 | Reviews: 2
Scraping: Do: Pilgrims of the Flying Temple...
  -> Scrape Success! Score: 7.82653 | Reviews: 49
Scraping: The Doctor Who Role Playing Game...
  -> Scrape Success! Score: 6.29412 | Reviews: 34
Scraping: Doctor Who Roleplaying Game...
  -> Scrape Success! Score: 7.38889 | Reviews: 9
Scraping: Time Lord...
  -> Scrape Success! Score: 5.625 | Reviews: 12
Scraping: Dog Eat Dog...
  -> Scrape Success! Score: 8.58333 | Reviews: 12
Scraping: Dogs in the Vineyard...
  -> Scrape Success! Score: 7.86889 | Reviews: 262
Scraping: Domination...
  -> Scrape Success! Score: 3 | Reviews: 1
Scraping: Dominion Rules...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: The Dominion Tank Police Role-Playing Game...
  -> Game not found in search results.
Scraping: Donjon...
  -> Scrape Success! Score: 6.5 | Reviews: 13
Scraping: Don't Look Back...
  -> Scrape Success! Score: 8 | Reviews: 2
Scraping: Don't Rest Your Head...
  -> Scrape Success! Score: 7.56742 | Reviews: 132
Scraping: Drací doupe...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Dragon Age...
  -> Scrape Success! Score: 7.60216 | Reviews: 102
Scraping: Dragonlance: Fifth Age...
  -> Scrape Success! Score: 6.94519 | Reviews: 52
Scraping: Dragon Lords of Melniboné...
  -> Scrape Success! Score: 4.83333 | Reviews: 12
Scraping: DragonMech...
  -> Scrape Success! Score: 7 | Reviews: 4
Scraping: DragonQuest...
  -> Scrape Success! Score: 7.34375 | Reviews: 32
Scraping: DragonRaid...
  -> Scrape Success! Score: 4.54545 | Reviews: 11
Scraping: Dragonroar...
  -> Scrape Success! Score: 4.5 | Reviews: 2
Scraping: Dragonstar...
  -> Scrape Success! Score: 6.66667 | Reviews: 6
Scraping: Dragon Storm...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Dragon Warriors...
  -> Scrape Success! Score: 7.69318 | Reviews: 44
Scraping: Drakar och Demoner...
  -> Scrape Success! Score: 7.06154 | Reviews: 13
Scraping: Dread RPG...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Dread: The First Book of Pandemonium...
  -> Scrape Success! Score: 7.125 | Reviews: 8
Scraping: Dream Askew, Dream Apart...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Dream Park: The Roleplaying Game...
  -> Game not found in search results.
Scraping: Dresden files rpg...
  -> Scrape Success! Score: 8.02322 | Reviews: 211
Scraping: Droids...
  -> Scrape Success! Score: 5.75 | Reviews: 4
Scraping: Dune: Chronicles of the Imperium...
  -> Scrape Success! Score: 7.27778 | Reviews: 27
Scraping: Dungeons & Dragons...
  -> Scrape Success! Score: 8.01501 | Reviews: 403
Scraping: Dungeon Crawl Classics...
  -> Scrape Success! Score: 8.25004 | Reviews: 280
Scraping: Dungeon Squad...
  -> Scrape Success! Score: 5 | Reviews: 4
Scraping: Dungeon World...
  -> Scrape Success! Score: 7.81411 | Reviews: 319
Scraping: Durance...
  -> Scrape Success! Score: 7.25 | Reviews: 28
Scraping: Dust Devils...
  -> Scrape Success! Score: 7.24038 | Reviews: 26
Scraping: The Dying Earth Roleplaying Game...
  -> Scrape Success! Score: 7.31143 | Reviews: 35
Scraping: Dzikie Pola...
  -> Scrape Success! Score: 7.3 | Reviews: 10
Scraping: EABA...
  -> Scrape Success! Score: 6.54545 | Reviews: 11
Scraping: Earth 2020...
  -> Game not found in search results.
Scraping: Earthdawn...
  -> Scrape Success! Score: 7.3619 | Reviews: 105
Scraping: Eat the Reich...
  -> Scrape Success! Score: 7.35 | Reviews: 20
Scraping: Eclipse Phase...
  -> Scrape Success! Score: 7.78099 | Reviews: 171
Scraping: Ehdrigohr...
  -> Scrape Success! Score: 6.5 | Reviews: 4
Scraping: El-Hazard Role-Playing Game...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Eldritch Role-Playing System...
  -> Scrape Success! Score: 6 | Reviews: 1
Scraping: Element Masters...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Elfquest...
  -> Scrape Success! Score: 6.17857 | Reviews: 14
Scraping: Elfs...
  -> Scrape Success! Score: 7 | Reviews: 3
Scraping: Elric!...
  -> Scrape Success! Score: 7.14909 | Reviews: 55
Scraping: Empire of the Petal Throne...
  -> Scrape Success! Score: 7.50476 | Reviews: 21
Scraping: En Garde!...
  -> Scrape Success! Score: 7.27273 | Reviews: 11
Scraping: The End...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Enforcers...
  -> Scrape Success! Score: 3.75 | Reviews: 4
Scraping: Engel...
  -> Scrape Success! Score: 6.61538 | Reviews: 13
Scraping: Eon...
  -> Scrape Success! Score: 6.13333 | Reviews: 6
Scraping: The Esoterrorists...
  -> Scrape Success! Score: 6.74043 | Reviews: 47
Scraping: Espionage!...
  -> Scrape Success! Score: 7.10714 | Reviews: 7
Scraping: Eternal Soldier...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: Etherscope...
  -> Scrape Success! Score: 6.40909 | Reviews: 11
Scraping: The Everlasting...
  -> Scrape Success! Score: 0 | Reviews: 0
Scraping: EverQuest Role-Playing Game...
  -> Scrape Success! Score: 5.92857 | Reviews: 14
Scraping: Everway...
  -> Scrape Success! Score: 7.15432 | Reviews: 81
Scraping: Ex Machina...
  -> Scrape Success! Score: 6.91176 | Reviews: 17
Scraping: Exalted...
  -> Scrape Success! Score: 6.81013 | Reviews: 79
Scraping: Exodus: Post Apocalyptic RPG...
  -> Scrape Success! Score: 5.66667 | Reviews: 3
Scraping: Expendables...
  -> Scrape Success! Score: 6.5 | Reviews: 2
Scraping: The Extraordinary Adventures of Baron Munchausen...
  -> Scrape Success! Score: 7.52574 | Reviews: 94
Scraping: Fading Suns...
  -> Scrape Success! Score: 7.15833 | Reviews: 60
Scraping: Fabula Ultima...
  -> Scrape Success! Score: 8.18182 | Reviews: 22
Scraping: Fanhunter, el juego de rol épicodecadente...

In [3]:
new_df.head()

,Name,Description,Average Score,Number of Reviews
0,13th Age,From the back cover:\n\nThe World Won't Save I...,7.90114,131
1,The 23rd Letter,From the publisher:\n\nThe time is now.\n\nPsy...,0,0
2,2300 AD,2300AD is a hard science-fiction role-playing ...,7.28917,60
3,3D&T,from the manual:\nEste guia n&atilde;o inclui ...,7,1
4,7th Sea,The first of two core rulebooks for the 7th Se...,7.57759,116

In [5]:
import pandas as pd
from bs4 import BeautifulSoup
import time
import random
import cloudscraper
import re
import json
import html

print("🚀 Starting the Fault-Tolerant Pure HTML TTRPG Scraper...")

# --- SETUP ---
# Set this to however many pages you want to scrape (100 pages = ~10,000 games)
MAX_PAGES_TO_SCRAPE = 1000
OUTPUT_FILENAME = "ttrpg_database_final.csv"

scraper = cloudscraper.create_scraper(
    browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
)

# ==========================================
# PHASE 1: HARVEST GAME LINKS (CORRECTED SESSION)
# ==========================================
import time
import random
from bs4 import BeautifulSoup
import re

game_links = []
MAX_PAGES_TO_SCRAPE = 100 

print(f"\n[PHASE 1] Harvesting {MAX_PAGES_TO_SCRAPE * 100} Game Links...")

# 🌟 THE FIX: We use the 'scraper' object directly. 
# It already acts as a persistent session and keeps your cookies!

for page in range(1, MAX_PAGES_TO_SCRAPE + 1):
    browse_url = f"https://boardgamegeek.com/browse/rpgitem/page/{page}"
    
    # Add a Referer to look like a real browsing path
    if page == 1:
        headers = {"Referer": "https://boardgamegeek.com/"}
    else:
        headers = {"Referer": f"https://boardgamegeek.com/browse/rpgitem/page/{page-1}"}

    print(f"  -> Scraping Browse Page {page:<3}...", end=" ")
    
    try:
        # Use scraper.get directly
        res = scraper.get(browse_url, headers=headers)
        
        # JITTER: Stay between 5 and 9 seconds to be very safe
        time.sleep(random.uniform(5.0, 9.0)) 
        
        if res.status_code == 200:
            # CHECK: Did Cloudflare give us a 'Just a moment' page?
            if "challenge-platform" in res.text or "Just a moment..." in res.text:
                print("| 🚨 Cloudflare Challenge detected! Try manually clearing in browser.")
                break

            soup = BeautifulSoup(res.content, 'html.parser')
            links = soup.find_all('a', href=re.compile(r'^/rpgitem/\d+/'))
            
            if not links:
                print("| 🚨 Zero links found. The page might be blank.")
                break

            for link in links:
                game_links.append(link['href'])
                
            current_unique = len(set(game_links))
            print(f"| 🎯 Total Unique Ready: {current_unique}")
            
            # --- THE COOLDOWN ---
            if page % 5 == 0:
                cooldown = random.randint(20, 40)
                print(f"     ☕ Cooldown... pausing for {cooldown}s...")
                time.sleep(cooldown)
                
        elif res.status_code == 403:
            print(f"| 🚨 403 Forbidden on Page {page}. IP is flagged.")
            break 
        else:
            print(f"| ⚠️ Failed. Status: {res.status_code}")
            
    except Exception as e:
        print(f"| Error: {e}")

game_links = list(set(game_links))
print(f"\n✅ Phase 1 Complete! Passing {len(game_links)} unique games to Phase 2.")

# ==========================================
# PHASE 2: SCRAPE INDIVIDUAL HTML PAGES
# ==========================================
print("\n[PHASE 2] Scraping Game Details (with Auto-Saving)...")
final_dataset = []

for index, link in enumerate(game_links):
    full_url = "https://boardgamegeek.com" + link
    search_name = link.split('/')[-1].replace('-', ' ').title() 
    
    # Print on the same line to keep the terminal clean
    print(f"  -> {index + 1}/{len(game_links)}: {search_name[:20]:<20}...", end=" ")
    
    try:
        res = scraper.get(full_url)
        # Jitter: Random sleep between 2.5 and 4.0 seconds (CRITICAL FOR HTML)
        time.sleep(random.uniform(2.5, 4.0)) 
        
        if res.status_code == 200:
            soup = BeautifulSoup(res.content, 'html.parser')
            
            # --- Extract Description ---
            desc = "No description"
            meta_desc = soup.find('meta', attrs={'name': 'description'})
            if meta_desc:
                desc = meta_desc['content']
                desc = html.unescape(desc)
                desc = re.sub(r"^\s*(From the publisher:|User summary:)\s*", "", desc, flags=re.IGNORECASE)
                desc = re.sub(r'\n+', ' ', desc)
                desc = re.sub(r'\s{2,}', ' ', desc).strip()
                
            # --- Extract Stats & Real Name ---
            avg_score = 0.0
            num_reviews = 0
            
            scripts = soup.find_all('script')
            for script in scripts:
                if script.string and 'GEEK.geekitemPreload' in script.string:
                    json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                    if json_match:
                        try:
                            data = json.loads(json_match.group(1))
                            stats = data.get('item', {}).get('stats', {})
                            avg_score = float(stats.get('average', 0.0))
                            num_reviews = int(stats.get('usersrated', 0))
                            
                            official_name = data.get('item', {}).get('name')
                            if official_name:
                                search_name = official_name
                        except json.JSONDecodeError:
                            pass
                    break 
                    
            final_dataset.append({
                'Name': search_name,
                'Description': desc,
                'Average Score': avg_score,
                'Number of Reviews': num_reviews
            })
            
            print(f"| Score: {avg_score:.2f} | Reviews: {num_reviews}")
            
        elif res.status_code == 429:
            print("| 🚨 Rate Limited! Pausing for 30 seconds...")
            time.sleep(30)
        elif res.status_code == 403:
            print("| 🚨 403 Forbidden! Cloudflare blocked you. Wait 15 mins.")
            time.sleep(30)
        else:
            print(f"| ⚠️ Failed Status: {res.status_code}")
            
    except Exception as e:
        print(f"| Error: {e}")
        
    # --- AUTO-CHECKPOINT SYSTEM ---
    # Every 50 games, save the current progress to the CSV
    if (index + 1) % 50 == 0:
        pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
        print(f"     💾 Checkpoint Reached: Saved {index + 1} rows to {OUTPUT_FILENAME}")

# ==========================================
# FINAL SAVE
# ==========================================
df = pd.DataFrame(final_dataset)
df.to_csv(OUTPUT_FILENAME, index=False)
print(f"\n🎉 FULLY COMPLETE! Scraped {len(df)} games and saved to '{OUTPUT_FILENAME}'")

🚀 Starting the Fault-Tolerant Pure HTML TTRPG Scraper...

[PHASE 1] Harvesting 10000 Game Links...
  -> Scraping Browse Page 1  ... | 🎯 Total Unique Ready: 100
  -> Scraping Browse Page 2  ... | 🎯 Total Unique Ready: 200
  -> Scraping Browse Page 3  ... | 🎯 Total Unique Ready: 300
  -> Scraping Browse Page 4  ... | 🎯 Total Unique Ready: 400
  -> Scraping Browse Page 5  ... | 🎯 Total Unique Ready: 499
     ☕ Cooldown... pausing for 34s...
  -> Scraping Browse Page 6  ... | 🎯 Total Unique Ready: 600
  -> Scraping Browse Page 7  ... | 🎯 Total Unique Ready: 700
  -> Scraping Browse Page 8  ... | 🎯 Total Unique Ready: 800
  -> Scraping Browse Page 9  ... | 🎯 Total Unique Ready: 900
  -> Scraping Browse Page 10 ... | 🎯 Total Unique Ready: 1000
     ☕ Cooldown... pausing for 27s...
  -> Scraping Browse Page 11 ... | 🚨 Zero links found. The page might be blank.

✅ Phase 1 Complete! Passing 1000 unique games to Phase 2.

[PHASE 2] Scraping Game Details (with Auto-Saving)...
  -> 1/1000: The Strange         ... | Score: 7.86 | Reviews: 37
  -> 2/1000: Inspectres          ... | Score: 7.57 | Reviews: 138
  -> 3/1000: Dungeons And Dragons... | Score: 7.98 | Reviews: 151
  -> 4/1000: The Character Compen... | Score: 8.09 | Reviews: 16
  -> 5/1000: The Elves Of Alfheim... | Score: 7.25 | Reviews: 41
  -> 6/1000: The Inner Sea World ... | Score: 8.06 | Reviews: 114
  -> 7/1000: Fudge               ... | Score: 7.56 | Reviews: 77
  -> 8/1000: Wizards Spell Compen... | Score: 7.94 | Reviews: 27
  -> 9/1000: The Shamutanti Hills... | Score: 7.77 | Reviews: 49
  -> 10/1000: The Pendragon Campai... | Score: 8.05 | Reviews: 19
  -> 11/1000: Swashbucklers Of The... | Score: 7.70 | Reviews: 30
  -> 12/1000: Ninth World Guideboo... | Score: 8.30 | Reviews: 15
  -> 13/1000: Dungeons And Dragons... | Score: 7.37 | Reviews: 71
  -> 14/1000: Moria The Dwarven Ci... | Score: 7.34 | Reviews: 39
  -> 15/1000: Arms Law Rmss       ... | Score: 7.59 | Reviews: 28
  -> 16/1000: The Hidden Shrine Of... | Score: 7.47 | Reviews: 76
  -> 17/1000: River Of Cradles    ... | Score: 7.87 | Reviews: 25
  -> 18/1000: Dungeon Master Guide... | Score: 7.04 | Reviews: 106
  -> 19/1000: The Great Maze      ... | Score: 7.94 | Reviews: 18
  -> 20/1000: Curse Of Strahd     ... | Score: 8.31 | Reviews: 157
  -> 21/1000: Art And Arcana A Vis... | Score: 8.97 | Reviews: 39
  -> 22/1000: 7Th Sea Core Ruleboo... | Score: 7.75 | Reviews: 55
  -> 23/1000: The Keep On The Bord... | Score: 7.65 | Reviews: 277
  -> 24/1000: Pathfinder Roleplayi... | Score: 7.55 | Reviews: 78
  -> 25/1000: Monstrous Compendium... | Score: 7.44 | Reviews: 49
  -> 26/1000: City Of Thieves     ... | Score: 7.51 | Reviews: 58
  -> 27/1000: Hall Of The Fire Gia... | Score: 7.51 | Reviews: 46
  -> 28/1000: Dragonbane Rulebook ... | Score: 8.45 | Reviews: 20
  -> 29/1000: Low Life            ... | Score: 8.04 | Reviews: 25
  -> 30/1000: Mythic Bastionland  ... | Score: 8.67 | Reviews: 21
  -> 31/1000: Keeper Screen       ... | Score: 8.49 | Reviews: 58
  -> 32/1000: Buffy The Vampire Sl... | Score: 6.96 | Reviews: 75
  -> 33/1000: The Ghost Tower Of I... | Score: 6.89 | Reviews: 62
  -> 34/1000: In The Labyrinth    ... | Score: 8.02 | Reviews: 62
  -> 35/1000: Mage The Ascension 2... | Score: 7.40 | Reviews: 115
  -> 36/1000: Pathfinder Chronicle... | Score: 7.64 | Reviews: 30
  -> 37/1000: Fiend Folio         ... | Score: 7.47 | Reviews: 269
  -> 38/1000: Eberron Campaign Gui... | Score: 7.29 | Reviews: 48
  -> 39/1000: Savage Worlds Deluxe... | Score: 7.93 | Reviews: 129
  -> 40/1000: D And D Essentials K... | Score: 8.11 | Reviews: 94
  -> 41/1000: Pulp Cthulhu        ... | Score: 8.17 | Reviews: 54
  -> 42/1000: Warhammer Campaign  ... | Score: 8.19 | Reviews: 45
  -> 43/1000: Encyclopedia Magica ... | Score: 7.62 | Reviews: 44
  -> 44/1000: Gurps Basic Set Camp... | Score: 7.71 | Reviews: 131
  -> 45/1000: Dawn Of The Emperors... | Score: 7.33 | Reviews: 47
  -> 46/1000: Big Rubble          ... | Score: 8.72 | Reviews: 16
  -> 47/1000: Tunnels And Trolls 7... | Score: 7.32 | Reviews: 32
  -> 48/1000: Secret Of The Slaver... | Score: 7.26 | Reviews: 75
  -> 49/1000: Van Richtens Guide T... | Score: 7.93 | Reviews: 28
  -> 50/1000: 76 Patrons          ... | Score: 7.62 | Reviews: 30
     💾 Checkpoint Reached: Saved 50 rows to ttrpg_database_final.csv
  -> 51/1000: Darkmatter Campaign ... | Score: 7.92 | Reviews: 56
  -> 52/1000: Changeling The Lost ... | Score: 7.67 | Reviews: 104
  -> 53/1000: Tome Of Salvation   ... | Score: 8.11 | Reviews: 65
  -> 54/1000: Emerald Empire 4Th E... | Score: 8.66 | Reviews: 28
  -> 55/1000: Burning Empires     ... | Score: 7.47 | Reviews: 92
  -> 56/1000: Mouse Guard 2Nd Edit... | Score: 8.20 | Reviews: 30
  -> 57/1000: The Asylum And Other... | Score: 7.25 | Reviews: 42
  -> 58/1000: The Warlock Of Firet... | Score: 7.20 | Reviews: 128
  -> 59/1000: Firefly Role Playing... | Score: 7.99 | Reviews: 38
  -> 60/1000: Ruins Of The North  ... | Score: 8.31 | Reviews: 27
  -> 61/1000: The Force Unleashed ... | Score: 7.37 | Reviews: 48
  -> 62/1000: Masks Of Nyarlathote... | Score: 9.09 | Reviews: 61
  -> 63/1000: Star Wars Force And ... | Score: 8.13 | Reviews: 85
  -> 64/1000: Promethean The Creat... | Score: 7.38 | Reviews: 41
  -> 65/1000: Dc Adventures Heros ... | Score: 7.91 | Reviews: 62
  -> 66/1000: Otherspace          ... | Score: 7.48 | Reviews: 30
  -> 67/1000: Savage Worlds Deluxe... | Score: 7.81 | Reviews: 175
  -> 68/1000: The Traveller Book  ... | Score: 8.18 | Reviews: 68
  -> 69/1000: Postmodern Magick   ... | Score: 8.25 | Reviews: 16
  -> 70/1000: The Caverns Of Thrac... | Score: 8.65 | Reviews: 30
  -> 71/1000: Tashas Cauldron Of E... | Score: 7.50 | Reviews: 62
  -> 72/1000: Cthulhu Spielleiter ... | Score: 7.93 | Reviews: 14
  -> 73/1000: Champions Of Mystara... | Score: 7.95 | Reviews: 23
  -> 74/1000: Tome Of Magic       ... | Score: 6.89 | Reviews: 106
  -> 75/1000: Tales From Wilderlan... | Score: 8.49 | Reviews: 70
  -> 76/1000: Vampire The Masquera... | Score: 7.43 | Reviews: 203
  -> 77/1000: Primetime Adventures... | Score: 7.68 | Reviews: 119
  -> 78/1000: Castle Amber Chateau... | Score: 7.47 | Reviews: 108
  -> 79/1000: Wizards Spell Compen... | Score: 7.91 | Reviews: 27
  -> 80/1000: Shadowdark Rpg Core ... | Score: 8.39 | Reviews: 28
  -> 81/1000: The Great Clans     ... | Score: 8.35 | Reviews: 20
  -> 82/1000: Cthulhu Confidential... | Score: 8.18 | Reviews: 16
  -> 83/1000: Dungeon Masters Guid... | Score: 7.92 | Reviews: 494
  -> 84/1000: Doctor Who Adventure... | Score: 7.60 | Reviews: 55
  -> 85/1000: Aaron Allstons Strik... | Score: 9.23 | Reviews: 11
  -> 86/1000: Gurps Martial Arts 4... | Score: 7.88 | Reviews: 24
  -> 87/1000: Waterdeep And The No... | Score: 7.25 | Reviews: 56
  -> 88/1000: Gurps Steampunk     ... | Score: 7.77 | Reviews: 26
  -> 89/1000: Lure Of Power       ... | Score: 8.02 | Reviews: 25
  -> 90/1000: Spherewalker Sourceb... | Score: 8.64 | Reviews: 14
  -> 91/1000: Legends Of Anglerre ... | Score: 7.42 | Reviews: 36
  -> 92/1000: Star Wars Force And ... | Score: 7.78 | Reviews: 20
  -> 93/1000: Angel Roleplaying Ga... | Score: 7.32 | Reviews: 38
  -> 94/1000: My Life With Master ... | Score: 7.48 | Reviews: 68
  -> 95/1000: Eyes Only           ... | Score: 8.20 | Reviews: 67
  -> 96/1000: Unknown Armies      ... | Score: 7.73 | Reviews: 47
  -> 97/1000: Disciples Of The Dar... | Score: 7.62 | Reviews: 60
  -> 98/1000: Enter The Unknown   ... | Score: 7.87 | Reviews: 37
  -> 99/1000: Lords Of Madness The... | Score: 7.36 | Reviews: 47
  -> 100/1000: Fantasy Craft       ... | Score: 7.65 | Reviews: 30
     💾 Checkpoint Reached: Saved 100 rows to ttrpg_database_final.csv
  -> 101/1000: Old School Reference... | Score: 7.89 | Reviews: 43
  -> 102/1000: The Golden Age Class... | Score: 8.78 | Reviews: 16
  -> 103/1000: Star Frontiers      ... | Score: 6.85 | Reviews: 119
  -> 104/1000: Marvel Super Heroes ... | Score: 7.08 | Reviews: 102
  -> 105/1000: Beyond The Rim      ... | Score: 7.81 | Reviews: 53
  -> 106/1000: Fiendish Codex Ii Ty... | Score: 7.57 | Reviews: 38
  -> 107/1000: Dungeons And Dragons... | Score: 7.76 | Reviews: 23
  -> 108/1000: Mansions Of Madness ... | Score: 7.83 | Reviews: 66
  -> 109/1000: Star Wars Edge Of Th... | Score: 8.24 | Reviews: 366
  -> 110/1000: Dungeons And Dragons... | Score: 7.76 | Reviews: 196
  -> 111/1000: Comme Il Faut       ... | Score: 8.28 | Reviews: 37
  -> 112/1000: Marvel Super Heroes ... | Score: 7.71 | Reviews: 110
  -> 113/1000: Land Of Ninja       ... | Score: 7.52 | Reviews: 33
  -> 114/1000: Mouse Guard Roleplay... | Score: 8.30 | Reviews: 107
  -> 115/1000: Scum And Villainy   ... | Score: 7.65 | Reviews: 38
  -> 116/1000: Merchant Prince     ... | Score: 7.36 | Reviews: 31
  -> 117/1000: Monstrous Compendium... | Score: 6.87 | Reviews: 98
  -> 118/1000: La Llamada De Cthulh... | Score: 8.51 | Reviews: 36
  -> 119/1000: Harn Regional Module... | Score: 8.41 | Reviews: 31
  -> 120/1000: Star Wars Age Of Reb... | Score: 7.94 | Reviews: 24
  -> 121/1000: Warhammer Fantasy Ro... | Score: 8.06 | Reviews: 72
  -> 122/1000: Stolen Land         ... | Score: 7.80 | Reviews: 41
  -> 123/1000: H P Lovecrafts Dream... | Score: 7.74 | Reviews: 43
  -> 124/1000: The Way Of The Scorp... | Score: 7.97 | Reviews: 39
  -> 125/1000: The Lost Caverns Of ... | Score: 7.68 | Reviews: 101
  -> 126/1000: The Winds Of Magic  ... | Score: 8.16 | Reviews: 49
  -> 127/1000: Advanced Melee      ... | Score: 7.83 | Reviews: 61
  -> 128/1000: The Ruins Of Undermo... | Score: 7.40 | Reviews: 83
  -> 129/1000: Dungeon Masters Guid... | Score: 6.60 | Reviews: 246
  -> 130/1000: Spell Law Rmss 3Rd E... | Score: 7.56 | Reviews: 31
  -> 131/1000: Masque Of The Red De... | Score: 7.76 | Reviews: 39
  -> 132/1000: Auroras Whole Realms... | Score: 7.65 | Reviews: 48
  -> 133/1000: Veins Of The Earth  ... | Score: 8.81 | Reviews: 26
  -> 134/1000: The Crown Of Kings  ... | Score: 8.06 | Reviews: 33
  -> 135/1000: 13Th Age Bestiary   ... | Score: 8.27 | Reviews: 22
  -> 136/1000: Gurps Horror Third E... | Score: 7.97 | Reviews: 24
  -> 137/1000: Swords And Wizardry ... | Score: 7.42 | Reviews: 40
  -> 138/1000: Rites Of Battle     ... | Score: 7.92 | Reviews: 24
  -> 139/1000: Spelljammer Ad And D... | Score: 7.43 | Reviews: 69
  -> 140/1000: Vampire The Requiem ... | Score: 6.92 | Reviews: 128
  -> 141/1000: Mutant Year Zero Cor... | Score: 8.40 | Reviews: 73
  -> 142/1000: Rough Magicks       ... | Score: 7.62 | Reviews: 32
  -> 143/1000: Characters And Comba... | Score: 7.71 | Reviews: 49
  -> 144/1000: Dark Heresy         ... | Score: 7.49 | Reviews: 273
  -> 145/1000: Heros Call          ... | Score: 8.64 | Reviews: 22
  -> 146/1000: Psirun Revised      ... | Score: 8.00 | Reviews: 17
  -> 147/1000: Runequest Starter Se... | Score: 9.04 | Reviews: 39
  -> 148/1000: Ironsworn Starforged... | Score: 8.62 | Reviews: 63
  -> 149/1000: Houses Of The Bloode... | Score: 7.42 | Reviews: 50
  -> 150/1000: Doors To Darkness   ... | Score: 7.82 | Reviews: 37
     💾 Checkpoint Reached: Saved 150 rows to ttrpg_database_final.csv
  -> 151/1000: Elder Secrets Of Glo... | Score: 7.60 | Reviews: 30
  -> 152/1000: Traveller Starter Ed... | Score: 7.82 | Reviews: 31
  -> 153/1000: Bushido 3Rd Edition ... | Score: 7.59 | Reviews: 39
  -> 154/1000: Star Trek Adventures... | Score: 7.46 | Reviews: 74
  -> 155/1000: Alien The Roleplayin... | Score: 8.25 | Reviews: 135
  -> 156/1000: Fading Suns Second E... | Score: 7.25 | Reviews: 53
  -> 157/1000: Dungeons And Dragons... | Score: 7.80 | Reviews: 103
  -> 158/1000: Ascension           ... | Score: 7.29 | Reviews: 41
  -> 159/1000: Dungeon Masters Scre... | Score: 7.73 | Reviews: 68
  -> 160/1000: Call Of Cthulhu 6Th ... | Score: 8.29 | Reviews: 524
  -> 161/1000: Kult 1St Edition    ... | Score: 7.58 | Reviews: 78
  -> 162/1000: Terror In Talabheim ... | Score: 7.35 | Reviews: 38
  -> 163/1000: Need To Know        ... | Score: 8.35 | Reviews: 23
  -> 164/1000: Jedi Academy Trainin... | Score: 7.48 | Reviews: 39
  -> 165/1000: Martial Power       ... | Score: 6.90 | Reviews: 77
  -> 166/1000: Legend Of The Five R... | Score: 8.14 | Reviews: 127
  -> 167/1000: We Be Goblins       ... | Score: 7.96 | Reviews: 63
  -> 168/1000: The Hole In The Oak ... | Score: 8.03 | Reviews: 17
  -> 169/1000: Ars Magica          ... | Score: 7.61 | Reviews: 32
  -> 170/1000: Numenera Discovery  ... | Score: 8.62 | Reviews: 28
  -> 171/1000: H P Lovecrafts Arkha... | Score: 8.02 | Reviews: 51
  -> 172/1000: Icons Superpowered R... | Score: 7.27 | Reviews: 36
  -> 173/1000: The Glacial Rift Of ... | Score: 7.27 | Reviews: 47
  -> 174/1000: Genesys Core Ruleboo... | Score: 8.10 | Reviews: 52
  -> 175/1000: Eclipse Phase Core R... | Score: 7.78 | Reviews: 171
  -> 176/1000: Amber Diceless Role ... | Score: 7.66 | Reviews: 161
  -> 177/1000: The Burning Wheel Mo... | Score: 7.75 | Reviews: 76
  -> 178/1000: Star Wars Roleplayin... | Score: 7.04 | Reviews: 96
  -> 179/1000: Horse Lords Of Rohan... | Score: 8.09 | Reviews: 26
  -> 180/1000: Traveller Core Ruleb... | Score: 8.33 | Reviews: 19
  -> 181/1000: Career Compendium   ... | Score: 7.52 | Reviews: 37
  -> 182/1000: Mordenkainens Tome O... | Score: 7.78 | Reviews: 69
  -> 183/1000: Twilight 2000       ... | Score: 6.94 | Reviews: 84
  -> 184/1000: The Temple Of Elemen... | Score: 7.55 | Reviews: 166
  -> 185/1000: Robins Laws Of Good ... | Score: 7.86 | Reviews: 99
  -> 186/1000: Savage Worlds Revise... | Score: 7.88 | Reviews: 40
  -> 187/1000: Reign               ... | Score: 7.36 | Reviews: 64
  -> 188/1000: Polaris Chivalric Tr... | Score: 7.98 | Reviews: 91
  -> 189/1000: Tomb Of The Lizard K... | Score: 7.02 | Reviews: 44
  -> 190/1000: The Dresden Files Ro... | Score: 8.02 | Reviews: 211
  -> 191/1000: Queen Of The Spiders... | Score: 8.00 | Reviews: 54
  -> 192/1000: Loremasters Screen A... | Score: 7.65 | Reviews: 62
  -> 193/1000: Wolsung Magia Wieku ... | Score: 8.44 | Reviews: 34
  -> 194/1000: James Bond 007      ... | Score: 7.70 | Reviews: 144
  -> 195/1000: Player Essentials He... | Score: 6.91 | Reviews: 79
  -> 196/1000: Players Handbook 2 D... | Score: 6.95 | Reviews: 193
  -> 197/1000: Nights Black Agents ... | Score: 8.15 | Reviews: 84
  -> 198/1000: The Universal Brothe... | Score: 7.90 | Reviews: 21
  -> 199/1000: The Village Of Homml... | Score: 7.52 | Reviews: 117
  -> 200/1000: World Of Darkness   ... | Score: 7.25 | Reviews: 242
     💾 Checkpoint Reached: Saved 200 rows to ttrpg_database_final.csv
  -> 201/1000: Dwellers Of The Forb... | Score: 0.00 | Reviews: 0
  -> 202/1000: Marshals Handbook   ... | Score: 8.12 | Reviews: 25
  -> 203/1000: The Grey Knight     ... | Score: 8.32 | Reviews: 22
  -> 204/1000: Designers And Dragon... | Score: 8.55 | Reviews: 19
  -> 205/1000: The Long Arm Of The ... | Score: 7.41 | Reviews: 46
  -> 206/1000: Dictionary Of Mu    ... | Score: 7.89 | Reviews: 29
  -> 207/1000: Artesia Adventures I... | Score: 7.36 | Reviews: 36
  -> 208/1000: Pathfinder Roleplayi... | Score: 7.98 | Reviews: 225
  -> 209/1000: Urban Shadows       ... | Score: 7.71 | Reviews: 41
  -> 210/1000: Magic Item Compendiu... | Score: 7.19 | Reviews: 67
  -> 211/1000: Chessex Double Sided... | Score: 8.52 | Reviews: 21
  -> 212/1000: The Inquisitors Hand... | Score: 7.37 | Reviews: 94
  -> 213/1000: The Republic Of Daro... | Score: 7.47 | Reviews: 33
  -> 214/1000: Kingdoms Of Kalamar ... | Score: 8.28 | Reviews: 36
  -> 215/1000: Npc Codex           ... | Score: 7.64 | Reviews: 29
  -> 216/1000: Serenity Role Playin... | Score: 6.73 | Reviews: 116
  -> 217/1000: Pharaoh             ... | Score: 7.81 | Reviews: 63
  -> 218/1000: Pathfinder Core Rule... | Score: 7.40 | Reviews: 65
  -> 219/1000: The Radicals Handboo... | Score: 7.70 | Reviews: 42
  -> 220/1000: Rules Compendium    ... | Score: 7.36 | Reviews: 47
  -> 221/1000: House Of Hell       ... | Score: 7.65 | Reviews: 55
  -> 222/1000: Tatters Of The King ... | Score: 7.99 | Reviews: 58
  -> 223/1000: The Star Wars Rolepl... | Score: 7.72 | Reviews: 130
  -> 224/1000: The Witchfire Trilog... | Score: 7.48 | Reviews: 22
  -> 225/1000: The Perilous Arts   ... | Score: 8.06 | Reviews: 16
  -> 226/1000: Call Of Cthulhu 1St ... | Score: 7.95 | Reviews: 73
  -> 227/1000: Horror On The Orient... | Score: 8.30 | Reviews: 61
  -> 228/1000: Gurps Basic Set Char... | Score: 7.67 | Reviews: 172
  -> 229/1000: Dungeons And Dragons... | Score: 7.99 | Reviews: 28
  -> 230/1000: Hackmaster Gamemaste... | Score: 8.41 | Reviews: 32
  -> 231/1000: Traders And Gunboats... | Score: 7.53 | Reviews: 38
  -> 232/1000: Legend Of The Five R... | Score: 8.06 | Reviews: 18
  -> 233/1000: The Ultimate Powers ... | Score: 7.78 | Reviews: 51
  -> 234/1000: Spell Compendium    ... | Score: 7.21 | Reviews: 70
  -> 235/1000: The Wfrp Companion  ... | Score: 7.23 | Reviews: 53
  -> 236/1000: Pathfinder Player Co... | Score: 8.33 | Reviews: 23
  -> 237/1000: Barony Of The Damned... | Score: 7.58 | Reviews: 42
  -> 238/1000: Weird West Players G... | Score: 7.93 | Reviews: 62
  -> 239/1000: The Arthurian Compan... | Score: 8.47 | Reviews: 20
  -> 240/1000: Tatooine Manhunt    ... | Score: 7.95 | Reviews: 55
  -> 241/1000: Stonehell Dungeon Do... | Score: 8.24 | Reviews: 26
  -> 242/1000: Cults Of Terror     ... | Score: 8.54 | Reviews: 27
  -> 243/1000: Players Handbook 3 D... | Score: 6.92 | Reviews: 77
  -> 244/1000: Iron Kingdoms Charac... | Score: 7.83 | Reviews: 49
  -> 245/1000: Wizards Spell Compen... | Score: 7.89 | Reviews: 28
  -> 246/1000: Monsternomicon Volum... | Score: 7.70 | Reviews: 35
  -> 247/1000: The Secret Of Bone H... | Score: 7.12 | Reviews: 70
  -> 248/1000: Vaesen              ... | Score: 8.01 | Reviews: 74
  -> 249/1000: Green And Pleasant L... | Score: 7.87 | Reviews: 34
  -> 250/1000: Omens Of War        ... | Score: 8.01 | Reviews: 35
     💾 Checkpoint Reached: Saved 250 rows to ttrpg_database_final.csv
  -> 251/1000: Stealing Cthulhu    ... | Score: 8.80 | Reviews: 29
  -> 252/1000: Call Of Cthulhu 3Rd ... | Score: 8.03 | Reviews: 125
  -> 253/1000: Lamentations Of The ... | Score: 7.27 | Reviews: 50
  -> 254/1000: Dungeons And Dragons... | Score: 8.02 | Reviews: 403
  -> 255/1000: Monte Cooks Arcana E... | Score: 7.85 | Reviews: 31
  -> 256/1000: The Jewel Of Yavin  ... | Score: 7.90 | Reviews: 26
  -> 257/1000: Space 1889          ... | Score: 7.12 | Reviews: 70
  -> 258/1000: Call Of Cthulhu 4Th ... | Score: 7.73 | Reviews: 98
  -> 259/1000: Glorantha Genertela ... | Score: 7.67 | Reviews: 36
  -> 260/1000: The Great Pendragon ... | Score: 8.97 | Reviews: 144
  -> 261/1000: Stars Without Number... | Score: 8.74 | Reviews: 34
  -> 262/1000: The 1920S Investigat... | Score: 7.51 | Reviews: 87
  -> 263/1000: Pathfinder Roleplayi... | Score: 7.86 | Reviews: 704
  -> 264/1000: D And D Character Bu... | Score: 8.00 | Reviews: 109
  -> 265/1000: Draconomicon The Boo... | Score: 7.16 | Reviews: 81
  -> 266/1000: Street Magic        ... | Score: 7.87 | Reviews: 31
  -> 267/1000: Tomb Of Annihilation... | Score: 8.35 | Reviews: 58
  -> 268/1000: Designers And Dragon... | Score: 8.54 | Reviews: 24
  -> 269/1000: The Classic Books   ... | Score: 8.05 | Reviews: 32
  -> 270/1000: Monster Manual 3    ... | Score: 7.62 | Reviews: 42
  -> 271/1000: Hollow Earth Expedit... | Score: 7.59 | Reviews: 78
  -> 272/1000: City State Of The In... | Score: 7.71 | Reviews: 39
  -> 273/1000: Werewolf The Apocaly... | Score: 7.09 | Reviews: 125
  -> 274/1000: Karma Sourcebook    ... | Score: 8.06 | Reviews: 17
  -> 275/1000: Lost Tomb Of Martek ... | Score: 7.67 | Reviews: 43
  -> 276/1000: Gurps Cabal         ... | Score: 8.21 | Reviews: 14
  -> 277/1000: Oriental Adventures ... | Score: 7.08 | Reviews: 138
  -> 278/1000: Death Frost Doom    ... | Score: 8.09 | Reviews: 32
  -> 279/1000: Shadowrun           ... | Score: 7.16 | Reviews: 117

In [6]:
df.head()

,Name,Description,Average Score,Number of Reviews
0,The Strange,Publisher Blurb: Beneath the orbits and atoms ...,7.86486,37
1,InSpectres,Fighting the Forces of Darkness so you don't h...,7.57355,138
2,Dungeons & Dragons Expert Set,The first version of the D&D Expert Set. It co...,7.97881,151
3,The Character Compendium,An unofficial supplement for Warhammer Fantasy...,8.09375,16
4,The Elves of Alfheim,"""This is the first Gazetteer to outline a non-...",7.24878,41

In [ ]:
import os
import time
import random
import re
import json
import html
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

print("🚀 Starting the Incremental Time-Slice TTRPG Scraper (with Path Pagination)...")

# --- SETUP ---
OUTPUT_FILENAME = "ttrpg_database_final.csv"
START_YEAR = 1980
END_YEAR = 2026

# Initialize the Cloudscraper session
scraper = cloudscraper.create_scraper(
    browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
)

# Human-like headers to spoof a real Chrome browser
human_headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://boardgamegeek.com/advsearch/rpgitem",
    "Sec-Ch-Ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"Windows"',
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Upgrade-Insecure-Requests": "1"
}

# ==========================================
# PHASE 1: HARVEST GAME LINKS (TIME-SLICE BY YEAR)
# ==========================================
game_links = []
print(f"\n[PHASE 1] Harvesting Game Links using Time-Slicing ({START_YEAR} to {END_YEAR})...")

for year in range(START_YEAR, END_YEAR + 1):
    print(f"\n📅 --- Searching Year: {year} ---")
    
    # Loop pages 1 to 10 for each year
    for page in range(1, 11): 
        
        # 🌟 THE FIX: BGG uses path-based pagination (/page/X), NOT query parameters (&page=X) 🌟
        if page == 1:
            search_url = f"https://boardgamegeek.com/search/rpgitem?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        else:
            search_url = f"https://boardgamegeek.com/search/rpgitem/page/{page}?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        
        print(f"  -> Scraping Page {page:<2}...", end=" ")
        
        try:
            res = scraper.get(search_url, headers=human_headers)
            
            # Jitter: Random sleep between 5.0 and 8.0 seconds
            time.sleep(random.uniform(5.0, 8.0)) 
            
            if res.status_code == 200:
                soup = BeautifulSoup(res.content, 'html.parser')
                raw_links = soup.find_all('a', href=re.compile(r'^/rpgitem/\d+/'))
                
                if not raw_links:
                    print("| 🚨 End of year reached. Moving to next year.")
                    break 
                
                previous_unique_count = len(set(game_links))
                
                # Deduplicate the raw links on this specific page first
                unique_page_links = set([link['href'] for link in raw_links])
                
                for link in unique_page_links:
                    game_links.append(link)
                    
                current_unique_count = len(set(game_links))
                print(f"| Found {len(unique_page_links):<3} links | 🎯 Total Unique Ready: {current_unique_count}")
                
                # If the count didn't change, BGG is feeding us duplicates! Break the loop!
                if current_unique_count == previous_unique_count:
                    print("     ⏭️ BGG is repeating pages. Moving to next year!")
                    break 
                
            elif res.status_code == 403:
                print("| 🚨 403 Blocked! Cloudflare caught us. (Switch to mobile hotspot!)")
                break 
            else:
                print(f"| ⚠️ Failed. Status: {res.status_code}")
                break
                
        except Exception as e:
            print(f"| Error: {e}")
            
    # --- YEARLY COOLDOWN ---
    cooldown = random.randint(15, 30)
    print(f"     ☕ Year {year} complete. Cooldown for {cooldown}s...")
    time.sleep(cooldown)

# Final clean deduplication before Phase 2
game_links = list(set(game_links))
print(f"\n✅ Phase 1 Complete! Passing {len(game_links)} unique games to Phase 2.")


# ==========================================
# PHASE 2: INCREMENTAL SCRAPING (SMART SKIP)
# ==========================================
print("\n[PHASE 2] Scraping Game Details (with Smart Skip)...")

existing_names = set()
final_dataset = []

# --- LOAD THE EXISTING DATASET ---
if os.path.exists(OUTPUT_FILENAME):
    try:
        existing_df = pd.read_csv(OUTPUT_FILENAME)
        existing_names = set(existing_df['Name'].str.lower().dropna())
        print(f"📦 Successfully loaded {len(existing_names)} existing games to skip.")
        
        final_dataset = existing_df.to_dict('records') 
    except Exception as e:
        print(f"⚠️ Could not load existing dataset: {e}")
else:
    print("⚠️ No existing CSV found. Starting fresh.")

# --- LOOP THROUGH NEW LINKS ---
for index, link in enumerate(game_links):
    full_url = "https://boardgamegeek.com" + link
    
    search_name = link.split('/')[-1].replace('-', ' ').title() 
    
    print(f"  -> {index + 1}/{len(game_links)}: {search_name[:20]:<20}...", end=" ")
    
    # 🌟 THE SMART SKIP 🌟
    if search_name.lower() in existing_names:
        print("| ⏭️ Skipped (Already in CSV)")
        continue
    
    try:
        res = scraper.get(full_url)
        time.sleep(random.uniform(2.5, 4.0)) 
        
        if res.status_code == 200:
            soup = BeautifulSoup(res.content, 'html.parser')
            
            desc = "No description"
            meta_desc = soup.find('meta', attrs={'name': 'description'})
            if meta_desc:
                desc = meta_desc['content']
                desc = html.unescape(desc)
                desc = re.sub(r"^\s*(From the publisher:|User summary:)\s*", "", desc, flags=re.IGNORECASE)
                desc = re.sub(r'\n+', ' ', desc)
                desc = re.sub(r'\s{2,}', ' ', desc).strip()
                
            avg_score = 0.0
            num_reviews = 0
            
            scripts = soup.find_all('script')
            for script in scripts:
                if script.string and 'GEEK.geekitemPreload' in script.string:
                    json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                    if json_match:
                        try:
                            data = json.loads(json_match.group(1))
                            stats = data.get('item', {}).get('stats', {})
                            avg_score = float(stats.get('average', 0.0))
                            num_reviews = int(stats.get('usersrated', 0))
                            
                            official_name = data.get('item', {}).get('name')
                            if official_name:
                                search_name = official_name
                        except json.JSONDecodeError:
                            pass
                    break 
                    
            final_dataset.append({
                'Name': search_name,
                'Description': desc,
                'Average Score': avg_score,
                'Number of Reviews': num_reviews
            })
            
            existing_names.add(search_name.lower())
            print(f"| ✅ Score: {avg_score:.2f} | Reviews: {num_reviews}")
            
        elif res.status_code == 429:
            print("| 🚨 Rate Limited! Pausing for 30 seconds...")
            time.sleep(30)
        elif res.status_code == 403:
            print("| 🚨 403 Forbidden! Cloudflare blocked you.")
            time.sleep(30)
        else:
            print(f"| ⚠️ Failed Status: {res.status_code}")
            
    except Exception as e:
        print(f"| Error: {e}")
        
    # --- AUTO-CHECKPOINT SYSTEM ---
    if (index + 1) % 50 == 0:
        pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
        print(f"     💾 Checkpoint Reached: Saved {len(final_dataset)} total rows to {OUTPUT_FILENAME}")

# ==========================================
# FINAL SAVE
# ==========================================
df = pd.DataFrame(final_dataset)
df.to_csv(OUTPUT_FILENAME, index=False)
print(f"\n🎉 FULLY COMPLETE! Database now has {len(df)} total games in '{OUTPUT_FILENAME}'")

🚀 Starting the Incremental Time-Slice TTRPG Scraper (with Path Pagination)...

[PHASE 1] Harvesting Game Links using Time-Slicing (1980 to 2026)...

📅 --- Searching Year: 1980 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 100
  -> Scraping Page 2 ... | Found 54  links | 🎯 Total Unique Ready: 154
  -> Scraping Page 3 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1980 complete. Cooldown for 26s...

📅 --- Searching Year: 1981 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 254
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 354
  -> Scraping Page 3 ... | Found 47  links | 🎯 Total Unique Ready: 401
  -> Scraping Page 4 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1981 complete. Cooldown for 29s...

📅 --- Searching Year: 1982 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 501
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 601
  -> Scraping Page 3 ... | Found 54  links | 🎯 Total Unique Ready: 655
  -> Scraping Page 4 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1982 complete. Cooldown for 19s...

📅 --- Searching Year: 1983 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 755
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 855
  -> Scraping Page 3 ... | Found 91  links | 🎯 Total Unique Ready: 946
  -> Scraping Page 4 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1983 complete. Cooldown for 19s...

📅 --- Searching Year: 1984 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 1046
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 1146
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 1246
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 1346
  -> Scraping Page 5 ... | Found 26  links | 🎯 Total Unique Ready: 1372
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1984 complete. Cooldown for 27s...

📅 --- Searching Year: 1985 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 1472
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 1572
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 1672
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 1772
  -> Scraping Page 5 ... | Found 91  links | 🎯 Total Unique Ready: 1863
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1985 complete. Cooldown for 16s...

📅 --- Searching Year: 1986 ---
  -> Scraping Page 1 ... | Found 99  links | 🎯 Total Unique Ready: 1962
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 2062
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 2162
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 2262
  -> Scraping Page 5 ... | Found 56  links | 🎯 Total Unique Ready: 2318
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1986 complete. Cooldown for 19s...

📅 --- Searching Year: 1987 ---
  -> Scraping Page 1 ... | Found 99  links | 🎯 Total Unique Ready: 2417
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 2517
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 2617
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 2717
  -> Scraping Page 5 ... | Found 34  links | 🎯 Total Unique Ready: 2751
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1987 complete. Cooldown for 30s...

📅 --- Searching Year: 1988 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 2851
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 2951
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 3051
  -> Scraping Page 4 ... | Found 85  links | 🎯 Total Unique Ready: 3136
  -> Scraping Page 5 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1988 complete. Cooldown for 19s...

📅 --- Searching Year: 1989 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 3236
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 3336
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 3436
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 3536
  -> Scraping Page 5 ... | Found 30  links | 🎯 Total Unique Ready: 3566
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1989 complete. Cooldown for 20s...

📅 --- Searching Year: 1990 ---
  -> Scraping Page 1 ... | Found 99  links | 🎯 Total Unique Ready: 3665
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 3765
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 3865
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 3965
  -> Scraping Page 5 ... | Found 62  links | 🎯 Total Unique Ready: 4027
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1990 complete. Cooldown for 27s...

📅 --- Searching Year: 1991 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 4127
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 4227
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 4327
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 4427
  -> Scraping Page 5 ... | Found 71  links | 🎯 Total Unique Ready: 4498
  -> Scraping Page 6 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1991 complete. Cooldown for 17s...

📅 --- Searching Year: 1992 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 4598
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 4698
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 4798
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 4898
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 4998
  -> Scraping Page 6 ... | Found 45  links | 🎯 Total Unique Ready: 5043
  -> Scraping Page 7 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1992 complete. Cooldown for 22s...

📅 --- Searching Year: 1993 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 5143
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 5243
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 5343
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 5443
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 5543
  -> Scraping Page 6 ... | Found 56  links | 🎯 Total Unique Ready: 5599
  -> Scraping Page 7 ... | Found 27  links | 🎯 Total Unique Ready: 5626
  -> Scraping Page 8 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1993 complete. Cooldown for 29s...

📅 --- Searching Year: 1994 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 5726
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 5826
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 5926
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 6026
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 6126
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 6226
  -> Scraping Page 7 ... | Found 29  links | 🎯 Total Unique Ready: 6255
  -> Scraping Page 8 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1994 complete. Cooldown for 15s...

📅 --- Searching Year: 1995 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 6355
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 6455
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 6555
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 6655
  -> Scraping Page 5 ... | Found 22  links | 🎯 Total Unique Ready: 6677
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 6777
  -> Scraping Page 7 ... | Found 35  links | 🎯 Total Unique Ready: 6812
  -> Scraping Page 8 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1995 complete. Cooldown for 23s...

📅 --- Searching Year: 1996 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 6912
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 7012
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 7112
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 7212
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 7312
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 7412
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 7512
  -> Scraping Page 8 ... | Found 4   links | 🎯 Total Unique Ready: 7516
  -> Scraping Page 9 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1996 complete. Cooldown for 15s...

📅 --- Searching Year: 1997 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 7616
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 7716
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 7816
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 7916
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 8016
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 8116
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 8216
  -> Scraping Page 8 ... | Found 30  links | 🎯 Total Unique Ready: 8246
  -> Scraping Page 9 ... | 🚨 End of year reached. Moving to next year.
     ☕ Year 1997 complete. Cooldown for 18s...

📅 --- Searching Year: 1998 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 8346
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 8446
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 8546
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 8646
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 8746
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 8846
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 8946
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 9046
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 9146
  -> Scraping Page 10... | Found 1   links | 🎯 Total Unique Ready: 9147
     ☕ Year 1998 complete. Cooldown for 24s...

📅 --- Searching Year: 1999 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 9247
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 9347
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 9447
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 9547
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 9647
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 9747
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 9847
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 9947
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 10047
  -> Scraping Page 10... | Found 61  links | 🎯 Total Unique Ready: 10108
     ☕ Year 1999 complete. Cooldown for 19s...

📅 --- Searching Year: 2000 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 10208
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 10308
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 10408
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 10508
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 10608
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 10708
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 10808
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 10908
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 11008
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 11108
     ☕ Year 2000 complete. Cooldown for 18s...

📅 --- Searching Year: 2001 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 11208
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 11308
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 11408
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 11508
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 11608
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 11708
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 11808
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 11908
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 12008
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 12108
     ☕ Year 2001 complete. Cooldown for 20s...

📅 --- Searching Year: 2002 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 12208
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 12308
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 12408
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 12508
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 12608
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 12708
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 12808
  -> Scraping Page 8 ... | Found 34  links | 🎯 Total Unique Ready: 12842
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 12942
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 13042
     ☕ Year 2002 complete. Cooldown for 26s...

📅 --- Searching Year: 2003 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 13142
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 13242
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 13342
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 13442
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 13542
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 13642
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 13742
  -> Scraping Page 8 ... | Found 55  links | 🎯 Total Unique Ready: 13797
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 13897
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 13997
     ☕ Year 2003 complete. Cooldown for 18s...

📅 --- Searching Year: 2004 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 14097
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 14197
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 14297
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 14397
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 14497
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 14597
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 14697
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 14797
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 14897
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 14997
     ☕ Year 2004 complete. Cooldown for 28s...

📅 --- Searching Year: 2005 ---
  -> Scraping Page 1 ... | Found 99  links | 🎯 Total Unique Ready: 15096
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 15196
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 15296
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 15396
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 15496
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 15596
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 15696
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 15796
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 15896
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 15996
     ☕ Year 2005 complete. Cooldown for 23s...

📅 --- Searching Year: 2006 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 16096
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 16196
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 16296
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 16396
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 16496
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 16596
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 16696
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 16796
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 16896
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 16996
     ☕ Year 2006 complete. Cooldown for 22s...

📅 --- Searching Year: 2007 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 17096
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 17196
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 17296
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 17396
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 17496
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 17596
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 17696
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 17796
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 17896
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 17996
     ☕ Year 2007 complete. Cooldown for 26s...

📅 --- Searching Year: 2008 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 18096
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 18196
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 18296
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 18396
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 18496
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 18596
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 18696
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 18796
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 18896
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 18996
     ☕ Year 2008 complete. Cooldown for 15s...

📅 --- Searching Year: 2009 ---
  -> Scraping Page 1 ... | Found 101 links | 🎯 Total Unique Ready: 19097
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 19197
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 19297
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 19397
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 19497
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 19597
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 19697
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 19797
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 19897
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 19997
     ☕ Year 2009 complete. Cooldown for 22s...

📅 --- Searching Year: 2010 ---
  -> Scraping Page 1 ... | Found 100 links | 🎯 Total Unique Ready: 20097
  -> Scraping Page 2 ... | Found 100 links | 🎯 Total Unique Ready: 20197
  -> Scraping Page 3 ... | Found 100 links | 🎯 Total Unique Ready: 20297
  -> Scraping Page 4 ... | Found 100 links | 🎯 Total Unique Ready: 20397
  -> Scraping Page 5 ... | Found 100 links | 🎯 Total Unique Ready: 20497
  -> Scraping Page 6 ... | Found 100 links | 🎯 Total Unique Ready: 20597
  -> Scraping Page 7 ... | Found 100 links | 🎯 Total Unique Ready: 20697
  -> Scraping Page 8 ... | Found 100 links | 🎯 Total Unique Ready: 20797
  -> Scraping Page 9 ... | Found 100 links | 🎯 Total Unique Ready: 20897
  -> Scraping Page 10... | Found 100 links | 🎯 Total Unique Ready: 20997

KeyboardInterrupt:

In [3]:
import os
import time
import random
import re
import json
import html
import math
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

print("🚀 Starting the Incremental Time-Slice TTRPG Scraper (Dynamic Rolling Quota)...")

# --- SETUP ---
OUTPUT_FILENAME = "ttrpg_database_final.csv"
START_YEAR = 1980
END_YEAR = 2026
TARGET_TOTAL_GAMES = 10000

# Initialize the Cloudscraper session
scraper = cloudscraper.create_scraper(
    browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
)

human_headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://boardgamegeek.com/advsearch/rpgitem",
    "Sec-Ch-Ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"Windows"',
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Upgrade-Insecure-Requests": "1"
}

# ==========================================
# PRE-FLIGHT: LOAD EXISTING DATA
# ==========================================
existing_names = set()
final_dataset = []
games_already_have = 0

if os.path.exists(OUTPUT_FILENAME):
    try:
        existing_df = pd.read_csv(OUTPUT_FILENAME)
        existing_names = set(existing_df['Name'].str.lower().dropna())
        final_dataset = existing_df.to_dict('records') 
        games_already_have = len(final_dataset)
        print(f"📦 Loaded {games_already_have} existing games from CSV.")
    except Exception as e:
        print(f"⚠️ Could not load existing dataset: {e}")
else:
    print("⚠️ No existing CSV found. Starting fresh.")

# Calculate exactly how many we need to scrape in Phase 2
target_needed = TARGET_TOTAL_GAMES - games_already_have
print(f"🎯 Total target remaining: {target_needed} games.")


# ==========================================
# PHASE 1: HARVEST GAME LINKS (DYNAMIC QUOTA)
# ==========================================
game_links = [] 
seen_hrefs = set() 
years_list = list(range(START_YEAR, END_YEAR + 1))

print(f"\n[PHASE 1] Harvesting Links with Rolling Deficit Tracker...")

for i, year in enumerate(years_list):
    if target_needed <= 0:
        print("\n✅ Target links secured! Ending Phase 1 early.")
        break

    remaining_years = len(years_list) - i
    # 🌟 THE FIX: Dynamic Quota calculation 🌟
    # If previous years fell short, this number naturally goes up!
    # Added a +10% buffer to account for skipped duplicates in Phase 2
    current_year_quota = math.ceil((target_needed / remaining_years) * 1.10) 
    
    print(f"\n📅 --- Searching Year: {year} | Target for this year: {current_year_quota} ---")
    year_links_collected = 0
    
    for page in range(1, 11): 
        if year_links_collected >= current_year_quota:
            print(f"  -> 🎯 Reached {current_year_quota} limit for {year}. Moving on.")
            break

        if page == 1:
            search_url = f"https://boardgamegeek.com/search/rpgitem?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        else:
            search_url = f"https://boardgamegeek.com/search/rpgitem/page/{page}?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        
        print(f"  -> Scraping Page {page:<2}...", end=" ")
        
        try:
            res = scraper.get(search_url, headers=human_headers)
            time.sleep(random.uniform(4.0, 7.0)) 
            
            if res.status_code == 200:
                soup = BeautifulSoup(res.content, 'html.parser')
                raw_links = soup.find_all('a', href=re.compile(r'^/rpgitem/\d+/'))
                
                if not raw_links:
                    print("| 🚨 End of year reached.")
                    break 
                
                previous_unique_count = len(seen_hrefs)
                unique_page_links = set([link['href'] for link in raw_links])
                
                added_this_page = 0
                for href in unique_page_links:
                    if href not in seen_hrefs and year_links_collected < current_year_quota:
                        seen_hrefs.add(href)
                        game_links.append((href, year)) 
                        year_links_collected += 1
                        added_this_page += 1
                
                print(f"| Added {added_this_page:<3} links | 🎯 Year Total: {year_links_collected}/{current_year_quota}")
                
                if len(seen_hrefs) == previous_unique_count:
                    print("     ⏭️ BGG is repeating pages. Moving to next year!")
                    break 
                
            elif res.status_code == 403:
                print("| 🚨 403 Blocked! Cloudflare caught us.")
                break 
            else:
                print(f"| ⚠️ Failed. Status: {res.status_code}")
                break
                
        except Exception as e:
            print(f"| Error: {e}")
            
    # Deduct the amount we successfully queued up from the overall total
    target_needed -= year_links_collected
    
    cooldown = random.randint(10, 20)
    print(f"     ☕ Year {year} complete. Cooldown for {cooldown}s...")
    print(f"     📊 Total links still needed for 10k: {target_needed if target_needed > 0 else 0}")
    time.sleep(cooldown)

print(f"\n✅ Phase 1 Complete! Passing {len(game_links)} unique game links to Phase 2.")


# ==========================================
# PHASE 2: INCREMENTAL SCRAPING 
# ==========================================
print("\n[PHASE 2] Scraping Game Details...")

for index, (link, year) in enumerate(game_links):
    if len(final_dataset) >= TARGET_TOTAL_GAMES:
        print(f"\n🏁 TARGET REACHED! We have exactly {TARGET_TOTAL_GAMES} games in the dataset.")
        break

    full_url = "https://boardgamegeek.com" + link
    search_name = link.split('/')[-1].replace('-', ' ').title() 
    
    print(f"  -> {index + 1}/{len(game_links)}: [{year}] {search_name[:15]:<15}...", end=" ")
    
    if search_name.lower() in existing_names:
        print("| ⏭️ Skipped (Already in CSV)")
        continue
    
    try:
        res = scraper.get(full_url)
        time.sleep(random.uniform(2.5, 4.0)) 
        
        if res.status_code == 200:
            soup = BeautifulSoup(res.content, 'html.parser')
            
            desc = "No description"
            meta_desc = soup.find('meta', attrs={'name': 'description'})
            if meta_desc:
                desc = meta_desc['content']
                desc = html.unescape(desc)
                desc = re.sub(r"^\s*(From the publisher:|User summary:)\s*", "", desc, flags=re.IGNORECASE)
                desc = re.sub(r'\n+', ' ', desc)
                desc = re.sub(r'\s{2,}', ' ', desc).strip()
                
            avg_score = 0.0
            num_reviews = 0
            
            scripts = soup.find_all('script')
            for script in scripts:
                if script.string and 'GEEK.geekitemPreload' in script.string:
                    json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                    if json_match:
                        try:
                            data = json.loads(json_match.group(1))
                            stats = data.get('item', {}).get('stats', {})
                            avg_score = float(stats.get('average', 0.0))
                            num_reviews = int(stats.get('usersrated', 0))
                            
                            official_name = data.get('item', {}).get('name')
                            if official_name:
                                search_name = official_name
                        except json.JSONDecodeError:
                            pass
                    break 
                    
            final_dataset.append({
                'Name': search_name,
                'Publishing Year': year,
                'Description': desc,
                'Average Score': avg_score,
                'Number of Reviews': num_reviews
            })
            
            existing_names.add(search_name.lower())
            print(f"| ✅ Score: {avg_score:.2f} | Total DB: {len(final_dataset)}")
            
        elif res.status_code == 429:
            print("| 🚨 Rate Limited! Pausing for 30 seconds...")
            time.sleep(30)
        elif res.status_code == 403:
            print("| 🚨 403 Forbidden! Cloudflare blocked you.")
            time.sleep(30)
        else:
            print(f"| ⚠️ Failed Status: {res.status_code}")
            
    except Exception as e:
        print(f"| Error: {e}")
        
    if (index + 1) % 50 == 0:
        pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
        print(f"     💾 Checkpoint Reached: Saved {len(final_dataset)} total rows.")

# ==========================================
# FINAL SAVE
# ==========================================
df = pd.DataFrame(final_dataset)
df.to_csv(OUTPUT_FILENAME, index=False)
print(f"\n🎉 FULLY COMPLETE! Database now has {len(df)} total games in '{OUTPUT_FILENAME}'")

🚀 Starting the Incremental Time-Slice TTRPG Scraper (Dynamic Rolling Quota)...
📦 Loaded 986 existing games from CSV.
🎯 Total target remaining: 9014 games.

[PHASE 1] Harvesting Links with Rolling Deficit Tracker...

📅 --- Searching Year: 1980 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/211
  -> Scraping Page 2 ... | Added 54  links | 🎯 Year Total: 154/211
  -> Scraping Page 3 ... | 🚨 End of year reached.
     ☕ Year 1980 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 8860

📅 --- Searching Year: 1981 | Target for this year: 212 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/212
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/212
  -> Scraping Page 3 ... | Added 12  links | 🎯 Year Total: 212/212
  -> 🎯 Reached 212 limit for 1981. Moving on.
     ☕ Year 1981 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 8648

📅 --- Searching Year: 1982 | Target for this year: 212 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/212
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/212
  -> Scraping Page 3 ... | Added 12  links | 🎯 Year Total: 212/212
  -> 🎯 Reached 212 limit for 1982. Moving on.
     ☕ Year 1982 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 8436

📅 --- Searching Year: 1983 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/211
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/211
  -> Scraping Page 3 ... | Added 11  links | 🎯 Year Total: 211/211
  -> 🎯 Reached 211 limit for 1983. Moving on.
     ☕ Year 1983 complete. Cooldown for 15s...
     📊 Total links still needed for 10k: 8225

📅 --- Searching Year: 1984 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/211
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/211
  -> Scraping Page 3 ... | Added 11  links | 🎯 Year Total: 211/211
  -> 🎯 Reached 211 limit for 1984. Moving on.
     ☕ Year 1984 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 8014

📅 --- Searching Year: 1985 | Target for this year: 210 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/210
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/210
  -> Scraping Page 3 ... | Added 10  links | 🎯 Year Total: 210/210
  -> 🎯 Reached 210 limit for 1985. Moving on.
     ☕ Year 1985 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 7804

📅 --- Searching Year: 1986 | Target for this year: 210 ---
  -> Scraping Page 1 ... | Added 99  links | 🎯 Year Total: 99/210
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 199/210
  -> Scraping Page 3 ... | Added 11  links | 🎯 Year Total: 210/210
  -> 🎯 Reached 210 limit for 1986. Moving on.
     ☕ Year 1986 complete. Cooldown for 16s...
     📊 Total links still needed for 10k: 7594

📅 --- Searching Year: 1987 | Target for this year: 209 ---
  -> Scraping Page 1 ... | Added 99  links | 🎯 Year Total: 99/209
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 199/209
  -> Scraping Page 3 ... | Added 10  links | 🎯 Year Total: 209/209
  -> 🎯 Reached 209 limit for 1987. Moving on.
     ☕ Year 1987 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 7385

📅 --- Searching Year: 1988 | Target for this year: 209 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/209
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/209
  -> Scraping Page 3 ... | Added 9   links | 🎯 Year Total: 209/209
  -> 🎯 Reached 209 limit for 1988. Moving on.
     ☕ Year 1988 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 7176

📅 --- Searching Year: 1989 | Target for this year: 208 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/208
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/208
  -> Scraping Page 3 ... | Added 8   links | 🎯 Year Total: 208/208
  -> 🎯 Reached 208 limit for 1989. Moving on.
     ☕ Year 1989 complete. Cooldown for 13s...
     📊 Total links still needed for 10k: 6968

📅 --- Searching Year: 1990 | Target for this year: 208 ---
  -> Scraping Page 1 ... | Added 99  links | 🎯 Year Total: 99/208
  -> Scraping Page 2 ... | Added 52  links | 🎯 Year Total: 151/208
  -> Scraping Page 3 ... | Added 57  links | 🎯 Year Total: 208/208
  -> 🎯 Reached 208 limit for 1990. Moving on.
     ☕ Year 1990 complete. Cooldown for 19s...
     📊 Total links still needed for 10k: 6760

📅 --- Searching Year: 1991 | Target for this year: 207 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/207
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/207
  -> Scraping Page 3 ... | Added 7   links | 🎯 Year Total: 207/207
  -> 🎯 Reached 207 limit for 1991. Moving on.
     ☕ Year 1991 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 6553

📅 --- Searching Year: 1992 | Target for this year: 206 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/206
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/206
  -> Scraping Page 3 ... | Added 6   links | 🎯 Year Total: 206/206
  -> 🎯 Reached 206 limit for 1992. Moving on.
     ☕ Year 1992 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 6347

📅 --- Searching Year: 1993 | Target for this year: 206 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/206
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/206
  -> Scraping Page 3 ... | Added 6   links | 🎯 Year Total: 206/206
  -> 🎯 Reached 206 limit for 1993. Moving on.
     ☕ Year 1993 complete. Cooldown for 15s...
     📊 Total links still needed for 10k: 6141

📅 --- Searching Year: 1994 | Target for this year: 205 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/205
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/205
  -> Scraping Page 3 ... | Added 5   links | 🎯 Year Total: 205/205
  -> 🎯 Reached 205 limit for 1994. Moving on.
     ☕ Year 1994 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 5936

📅 --- Searching Year: 1995 | Target for this year: 205 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/205
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/205
  -> Scraping Page 3 ... | Added 5   links | 🎯 Year Total: 205/205
  -> 🎯 Reached 205 limit for 1995. Moving on.
     ☕ Year 1995 complete. Cooldown for 16s...
     📊 Total links still needed for 10k: 5731

📅 --- Searching Year: 1996 | Target for this year: 204 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/204
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/204
  -> Scraping Page 3 ... | Added 4   links | 🎯 Year Total: 204/204
  -> 🎯 Reached 204 limit for 1996. Moving on.
     ☕ Year 1996 complete. Cooldown for 16s...
     📊 Total links still needed for 10k: 5527

📅 --- Searching Year: 1997 | Target for this year: 203 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/203
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/203
  -> Scraping Page 3 ... | Added 3   links | 🎯 Year Total: 203/203
  -> 🎯 Reached 203 limit for 1997. Moving on.
     ☕ Year 1997 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 5324

📅 --- Searching Year: 1998 | Target for this year: 202 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/202
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/202
  -> Scraping Page 3 ... | Added 2   links | 🎯 Year Total: 202/202
  -> 🎯 Reached 202 limit for 1998. Moving on.
     ☕ Year 1998 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 5122

📅 --- Searching Year: 1999 | Target for this year: 202 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/202
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/202
  -> Scraping Page 3 ... | Added 2   links | 🎯 Year Total: 202/202
  -> 🎯 Reached 202 limit for 1999. Moving on.
     ☕ Year 1999 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 4920

📅 --- Searching Year: 2000 | Target for this year: 201 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/201
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/201
  -> Scraping Page 3 ... | Added 1   links | 🎯 Year Total: 201/201
  -> 🎯 Reached 201 limit for 2000. Moving on.
     ☕ Year 2000 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 4719

📅 --- Searching Year: 2001 | Target for this year: 200 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/200
  -> Scraping Page 2 ... | Added 100 links | 🎯 Year Total: 200/200
  -> 🎯 Reached 200 limit for 2001. Moving on.
     ☕ Year 2001 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 4519

📅 --- Searching Year: 2002 | Target for this year: 199 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/199
  -> Scraping Page 2 ... | Added 99  links | 🎯 Year Total: 199/199
  -> 🎯 Reached 199 limit for 2002. Moving on.
     ☕ Year 2002 complete. Cooldown for 13s...
     📊 Total links still needed for 10k: 4320

📅 --- Searching Year: 2003 | Target for this year: 199 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/199
  -> Scraping Page 2 ... | Added 99  links | 🎯 Year Total: 199/199
  -> 🎯 Reached 199 limit for 2003. Moving on.
     ☕ Year 2003 complete. Cooldown for 16s...
     📊 Total links still needed for 10k: 4121

📅 --- Searching Year: 2004 | Target for this year: 198 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/198
  -> Scraping Page 2 ... | Added 98  links | 🎯 Year Total: 198/198
  -> 🎯 Reached 198 limit for 2004. Moving on.
     ☕ Year 2004 complete. Cooldown for 11s...
     📊 Total links still needed for 10k: 3923

📅 --- Searching Year: 2005 | Target for this year: 197 ---
  -> Scraping Page 1 ... | Added 99  links | 🎯 Year Total: 99/197
  -> Scraping Page 2 ... | Added 98  links | 🎯 Year Total: 197/197
  -> 🎯 Reached 197 limit for 2005. Moving on.
     ☕ Year 2005 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 3726

📅 --- Searching Year: 2006 | Target for this year: 196 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/196
  -> Scraping Page 2 ... | Added 96  links | 🎯 Year Total: 196/196
  -> 🎯 Reached 196 limit for 2006. Moving on.
     ☕ Year 2006 complete. Cooldown for 20s...
     📊 Total links still needed for 10k: 3530

📅 --- Searching Year: 2007 | Target for this year: 195 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/195
  -> Scraping Page 2 ... | Added 95  links | 🎯 Year Total: 195/195
  -> 🎯 Reached 195 limit for 2007. Moving on.
     ☕ Year 2007 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 3335

📅 --- Searching Year: 2008 | Target for this year: 194 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/194
  -> Scraping Page 2 ... | Added 94  links | 🎯 Year Total: 194/194
  -> 🎯 Reached 194 limit for 2008. Moving on.
     ☕ Year 2008 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 3141

📅 --- Searching Year: 2009 | Target for this year: 192 ---
  -> Scraping Page 1 ... | Added 101 links | 🎯 Year Total: 101/192
  -> Scraping Page 2 ... | Added 91  links | 🎯 Year Total: 192/192
  -> 🎯 Reached 192 limit for 2009. Moving on.
     ☕ Year 2009 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 2949

📅 --- Searching Year: 2010 | Target for this year: 191 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/191
  -> Scraping Page 2 ... | Added 91  links | 🎯 Year Total: 191/191
  -> 🎯 Reached 191 limit for 2010. Moving on.
     ☕ Year 2010 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 2758

📅 --- Searching Year: 2011 | Target for this year: 190 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/190
  -> Scraping Page 2 ... | Added 90  links | 🎯 Year Total: 190/190
  -> 🎯 Reached 190 limit for 2011. Moving on.
     ☕ Year 2011 complete. Cooldown for 15s...
     📊 Total links still needed for 10k: 2568

📅 --- Searching Year: 2012 | Target for this year: 189 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/189
  -> Scraping Page 2 ... | Added 89  links | 🎯 Year Total: 189/189
  -> 🎯 Reached 189 limit for 2012. Moving on.
     ☕ Year 2012 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 2379

📅 --- Searching Year: 2013 | Target for this year: 187 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/187
  -> Scraping Page 2 ... | Added 87  links | 🎯 Year Total: 187/187
  -> 🎯 Reached 187 limit for 2013. Moving on.
     ☕ Year 2013 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 2192

📅 --- Searching Year: 2014 | Target for this year: 186 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/186
  -> Scraping Page 2 ... | Added 86  links | 🎯 Year Total: 186/186
  -> 🎯 Reached 186 limit for 2014. Moving on.
     ☕ Year 2014 complete. Cooldown for 20s...
     📊 Total links still needed for 10k: 2006

📅 --- Searching Year: 2015 | Target for this year: 184 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/184
  -> Scraping Page 2 ... | Added 84  links | 🎯 Year Total: 184/184
  -> 🎯 Reached 184 limit for 2015. Moving on.
     ☕ Year 2015 complete. Cooldown for 19s...
     📊 Total links still needed for 10k: 1822

📅 --- Searching Year: 2016 | Target for this year: 183 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/183
  -> Scraping Page 2 ... | Added 83  links | 🎯 Year Total: 183/183
  -> 🎯 Reached 183 limit for 2016. Moving on.
     ☕ Year 2016 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 1639

📅 --- Searching Year: 2017 | Target for this year: 181 ---
  -> Scraping Page 1 ... | Added 99  links | 🎯 Year Total: 99/181
  -> Scraping Page 2 ... | Added 82  links | 🎯 Year Total: 181/181
  -> 🎯 Reached 181 limit for 2017. Moving on.
     ☕ Year 2017 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 1458

📅 --- Searching Year: 2018 | Target for this year: 179 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/179
  -> Scraping Page 2 ... | Added 79  links | 🎯 Year Total: 179/179
  -> 🎯 Reached 179 limit for 2018. Moving on.
     ☕ Year 2018 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 1279

📅 --- Searching Year: 2019 | Target for this year: 176 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/176
  -> Scraping Page 2 ... | Added 76  links | 🎯 Year Total: 176/176
  -> 🎯 Reached 176 limit for 2019. Moving on.
     ☕ Year 2019 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 1103

📅 --- Searching Year: 2020 | Target for this year: 174 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/174
  -> Scraping Page 2 ... | Added 74  links | 🎯 Year Total: 174/174
  -> 🎯 Reached 174 limit for 2020. Moving on.
     ☕ Year 2020 complete. Cooldown for 19s...
     📊 Total links still needed for 10k: 929

📅 --- Searching Year: 2021 | Target for this year: 171 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/171
  -> Scraping Page 2 ... | Added 71  links | 🎯 Year Total: 171/171
  -> 🎯 Reached 171 limit for 2021. Moving on.
     ☕ Year 2021 complete. Cooldown for 14s...
     📊 Total links still needed for 10k: 758

📅 --- Searching Year: 2022 | Target for this year: 167 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/167
  -> Scraping Page 2 ... | Added 67  links | 🎯 Year Total: 167/167
  -> 🎯 Reached 167 limit for 2022. Moving on.
     ☕ Year 2022 complete. Cooldown for 12s...
     📊 Total links still needed for 10k: 591

📅 --- Searching Year: 2023 | Target for this year: 163 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/163
  -> Scraping Page 2 ... | Added 63  links | 🎯 Year Total: 163/163
  -> 🎯 Reached 163 limit for 2023. Moving on.
     ☕ Year 2023 complete. Cooldown for 10s...
     📊 Total links still needed for 10k: 428

📅 --- Searching Year: 2024 | Target for this year: 157 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/157
  -> Scraping Page 2 ... | Added 57  links | 🎯 Year Total: 157/157
  -> 🎯 Reached 157 limit for 2024. Moving on.
     ☕ Year 2024 complete. Cooldown for 19s...
     📊 Total links still needed for 10k: 271

📅 --- Searching Year: 2025 | Target for this year: 150 ---
  -> Scraping Page 1 ... | Added 102 links | 🎯 Year Total: 102/150
  -> Scraping Page 2 ... | Added 48  links | 🎯 Year Total: 150/150
  -> 🎯 Reached 150 limit for 2025. Moving on.
     ☕ Year 2025 complete. Cooldown for 13s...
     📊 Total links still needed for 10k: 121

📅 --- Searching Year: 2026 | Target for this year: 134 ---
  -> Scraping Page 1 ... | Added 100 links | 🎯 Year Total: 100/134
  -> Scraping Page 2 ... | Added 34  links | 🎯 Year Total: 134/134
  -> 🎯 Reached 134 limit for 2026. Moving on.
     ☕ Year 2026 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 0

✅ Phase 1 Complete! Passing 9027 unique game links to Phase 2.

[PHASE 2] Scraping Game Details...
  -> 1/9027: [1980] Leviathan      ... | ✅ Score: 7.32 | Total DB: 987
  -> 2/9027: [1980] Treasure Of The... | ✅ Score: 7.00 | Total DB: 988
  -> 3/9027: [1980] Land Of The Ris... | ✅ Score: 5.50 | Total DB: 989
  -> 4/9027: [1980] The Isle Of Dre... | ⏭️ Skipped (Already in CSV)
  -> 5/9027: [1980] Laserburn      ... | ✅ Score: 6.00 | Total DB: 990
  -> 6/9027: [1980] Skull And Cross... | ✅ Score: 8.00 | Total DB: 991
  -> 7/9027: [1980] The City Of Car... | ✅ Score: 7.75 | Total DB: 992
  -> 8/9027: [1980] The Mystery Of ... | ✅ Score: 6.67 | Total DB: 993
  -> 9/9027: [1980] Moorguard      ... | ✅ Score: 0.00 | Total DB: 994
  -> 10/9027: [1980] Advanced Melee ... | ⏭️ Skipped (Already in CSV)
  -> 11/9027: [1980] Thieves Guild  ... | ✅ Score: 7.33 | Total DB: 995
  -> 12/9027: [1980] Research Statio... | ✅ Score: 6.84 | Total DB: 996
  -> 13/9027: [1980] The Astrogators... | ✅ Score: 6.29 | Total DB: 997
  -> 14/9027: [1980] The Keep On The... | ⏭️ Skipped (Already in CSV)
  -> 15/9027: [1980] Hazard Ipsp Isi... | ✅ Score: 5.00 | Total DB: 998
  -> 16/9027: [1980] Space Opera    ... | ✅ Score: 6.29 | Total DB: 999
  -> 17/9027: [1980] The Unknown God... | ✅ Score: 6.40 | Total DB: 1000
  -> 18/9027: [1980] The Hidden Shri... | ⏭️ Skipped (Already in CSV)
  -> 19/9027: [1980] Death Test 2   ... | ✅ Score: 7.81 | Total DB: 1001
  -> 20/9027: [1980] Operation Rapid... | ✅ Score: 6.21 | Total DB: 1002
  -> 21/9027: [1980] Dragonquest Gam... | ✅ Score: 6.00 | Total DB: 1003
  -> 22/9027: [1980] Runemasters    ... | ✅ Score: 6.00 | Total DB: 1004
  -> 23/9027: [1980] Knights And Ber... | ✅ Score: 0.00 | Total DB: 1005
  -> 24/9027: [1980] Warlocks Menage... | ✅ Score: 7.00 | Total DB: 1006
  -> 25/9027: [1980] Dungeon Masters... | ✅ Score: 5.68 | Total DB: 1007
  -> 26/9027: [1980] Runequest 2Nd E... | ✅ Score: 7.88 | Total DB: 1008
  -> 27/9027: [1980] In The Labyrint... | ⏭️ Skipped (Already in CSV)
  -> 28/9027: [1980] Ispmv Tethys   ... | ✅ Score: 7.17 | Total DB: 1009
  -> 29/9027: [1980] Basic Role Play... | ✅ Score: 6.10 | Total DB: 1010
  -> 30/9027: [1980] Traveller Dice ... | ✅ Score: 8.67 | Total DB: 1011
  -> 31/9027: [1980] Deities And Dem... | ✅ Score: 7.64 | Total DB: 1012
  -> 32/9027: [1980] Wilderlands Of ... | ✅ Score: 7.80 | Total DB: 1013
  -> 33/9027: [1980] Monster And Tre... | ✅ Score: 6.09 | Total DB: 1014
  -> 34/9027: [1980] Death Heart    ... | ✅ Score: 6.20 | Total DB: 1015
  -> 35/9027: [1980] The Iron Wind  ... | ✅ Score: 0.00 | Total DB: 1016
  -> 36/9027: [1980] Inferno        ... | ✅ Score: 8.50 | Total DB: 1017
  -> 37/9027: [1980] The Temple To A... | ✅ Score: 0.00 | Total DB: 1018

KeyboardInterrupt:

In [5]:
import os
import time
import random
import re
import json
import html
import math
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

print("🚀 Starting the Incremental Time-Slice TTRPG Scraper (Clean Slate - Pre-Skip Edition)...")

# --- SETUP ---
OUTPUT_FILENAME = "ttrpg_database_final.csv"
START_YEAR = 1982  # <--- Change this from 1980 to 1982
END_YEAR = 2026
TARGET_TOTAL_GAMES = 10000

scraper = cloudscraper.create_scraper(
    browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
)

human_headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://boardgamegeek.com/advsearch/rpgitem",
    "Sec-Ch-Ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"Windows"',
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Upgrade-Insecure-Requests": "1"
}

# ==========================================
# PRE-FLIGHT: LOAD EXISTING DATA
# ==========================================
existing_names = set()
normalized_existing_names = set() # For aggressive Phase 1 pre-skipping
final_dataset = []
games_already_have = 0

if os.path.exists(OUTPUT_FILENAME):
    try:
        existing_df = pd.read_csv(OUTPUT_FILENAME)
        
        # Standard exact match for Phase 2
        existing_names = set(existing_df['Name'].str.lower().dropna())
        
        # Aggressive alphanumeric match for Phase 1 URL checking
        normalized_existing_names = set(
            re.sub(r'[^a-z0-9]', '', str(name).lower()) for name in existing_names
        )
        
        final_dataset = existing_df.to_dict('records') 
        games_already_have = len(final_dataset)
        print(f"📦 Loaded {games_already_have} existing games from CSV.")
    except Exception as e:
        print(f"⚠️ Could not load existing dataset: {e}")
else:
    print("⚠️ No existing CSV found. Starting fresh.")

target_needed = TARGET_TOTAL_GAMES - games_already_have
print(f"🎯 Total target remaining: {target_needed} games.")


# ==========================================
# PHASE 1: HARVEST GAME LINKS (PRE-SKIP DYNAMIC QUOTA)
# ==========================================
game_links = [] 
seen_hrefs = set() 
years_list = list(range(START_YEAR, END_YEAR + 1))

print(f"\n[PHASE 1] Harvesting Links with Pre-Skip Logic...")

for i, year in enumerate(years_list):
    if target_needed <= 0:
        print("\n✅ Target links secured! Ending Phase 1 early.")
        break

    remaining_years = len(years_list) - i
    # 🌟 NEW LOGIC: Calculate quota and add a strict 10% buffer to compensate for edge-cases
    current_year_quota = math.ceil((target_needed / remaining_years) * 1.10) 
    
    print(f"\n📅 --- Searching Year: {year} | Target for this year: {current_year_quota} ---")
    year_links_collected = 0
    
    for page in range(1, 11): 
        if year_links_collected >= current_year_quota:
            print(f"  -> 🎯 Reached {current_year_quota} limit for {year}. Moving on.")
            break

        if page == 1:
            search_url = f"https://boardgamegeek.com/search/rpgitem?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        else:
            search_url = f"https://boardgamegeek.com/search/rpgitem/page/{page}?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        
        print(f"  -> Scraping Page {page:<2}...", end=" ")
        
        try:
            res = scraper.get(search_url, headers=human_headers)
            time.sleep(random.uniform(4.0, 7.0)) 
            
            if res.status_code == 200:
                soup = BeautifulSoup(res.content, 'html.parser')
                raw_links = soup.find_all('a', href=re.compile(r'^/rpgitem/\d+/'))
                
                if not raw_links:
                    print("| 🚨 End of year reached.")
                    break 
                
                previous_unique_count = len(seen_hrefs)
                unique_page_links = set([link['href'] for link in raw_links])
                
                added_this_page = 0
                skipped_this_page = 0
                
                for href in unique_page_links:
                    if year_links_collected >= current_year_quota:
                        break

                    if href not in seen_hrefs:
                        # 🌟 PHASE 1 PRE-SKIP: Check URL name against existing DB
                        url_rough_name = re.sub(r'[^a-z0-9]', '', href.split('/')[-1].lower())
                        
                        if url_rough_name in normalized_existing_names:
                            seen_hrefs.add(href)
                            skipped_this_page += 1
                            continue # Do NOT count this toward the quota!
                        
                        seen_hrefs.add(href)
                        game_links.append((href, year)) 
                        year_links_collected += 1
                        added_this_page += 1
                
                print(f"| Added: {added_this_page:<3} | Pre-Skipped: {skipped_this_page:<3} | 🎯 Year Total: {year_links_collected}/{current_year_quota}")
                
                if len(seen_hrefs) == previous_unique_count:
                    print("     ⏭️ BGG is repeating pages. Moving to next year!")
                    break 
                
            elif res.status_code == 403:
                print("| 🚨 403 Blocked! Cloudflare caught us.")
                break 
            else:
                print(f"| ⚠️ Failed. Status: {res.status_code}")
                break
                
        except Exception as e:
            print(f"| Error: {e}")
            
    # Deduct ONLY the highly-likely-to-be-new links from our target
    target_needed -= year_links_collected
    
    cooldown = random.randint(10, 20)
    print(f"     ☕ Year {year} complete. Cooldown for {cooldown}s...")
    print(f"     📊 Total links still needed for 10k: {target_needed if target_needed > 0 else 0}")
    time.sleep(cooldown)

print(f"\n✅ Phase 1 Complete! Passing {len(game_links)} prime game links to Phase 2.")


# ==========================================
# PHASE 2: INCREMENTAL SCRAPING 
# ==========================================
print("\n[PHASE 2] Scraping Game Details...")

for index, (link, year) in enumerate(game_links):
    if len(final_dataset) >= TARGET_TOTAL_GAMES:
        print(f"\n🏁 TARGET REACHED! We have exactly {TARGET_TOTAL_GAMES} games in the dataset.")
        break

    full_url = "https://boardgamegeek.com" + link
    search_name = link.split('/')[-1].replace('-', ' ').title() 
    
    print(f"  -> {index + 1}/{len(game_links)}: [{year}] {search_name[:15]:<15}...", end=" ")
    
    if search_name.lower() in existing_names:
        print("| ⏭️ Skipped (Already in CSV)")
        continue
    
    try:
        res = scraper.get(full_url)
        time.sleep(random.uniform(2.5, 4.0)) 
        
        if res.status_code == 200:
            soup = BeautifulSoup(res.content, 'html.parser')
            
            desc = "No description"
            meta_desc = soup.find('meta', attrs={'name': 'description'})
            if meta_desc:
                desc = meta_desc['content']
                desc = html.unescape(desc)
                desc = re.sub(r"^\s*(From the publisher:|User summary:)\s*", "", desc, flags=re.IGNORECASE)
                desc = re.sub(r'\n+', ' ', desc)
                desc = re.sub(r'\s{2,}', ' ', desc).strip()
                
            avg_score = 0.0
            num_reviews = 0
            
            scripts = soup.find_all('script')
            for script in scripts:
                if script.string and 'GEEK.geekitemPreload' in script.string:
                    json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                    if json_match:
                        try:
                            data = json.loads(json_match.group(1))
                            stats = data.get('item', {}).get('stats', {})
                            avg_score = float(stats.get('average', 0.0))
                            num_reviews = int(stats.get('usersrated', 0))
                            
                            official_name = data.get('item', {}).get('name')
                            if official_name:
                                search_name = official_name
                        except json.JSONDecodeError:
                            pass
                    break 
                    
            final_dataset.append({
                'Name': search_name,
                'Publishing Year': year,
                'Description': desc,
                'Average Score': avg_score,
                'Number of Reviews': num_reviews
            })
            
            existing_names.add(search_name.lower())
            print(f"| ✅ Score: {avg_score:.2f} | Total DB: {len(final_dataset)}")
            
        elif res.status_code == 429:
            print("| 🚨 Rate Limited! Pausing for 30 seconds...")
            time.sleep(30)
        elif res.status_code == 403:
            print("| 🚨 403 Forbidden! Cloudflare blocked you.")
            time.sleep(30)
        else:
            print(f"| ⚠️ Failed Status: {res.status_code}")
            
    except Exception as e:
        print(f"| Error: {e}")
        
    if (index + 1) % 50 == 0:
        pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
        print(f"     💾 Checkpoint Reached: Saved {len(final_dataset)} total rows.")

# ==========================================
# FINAL SAVE
# ==========================================
df = pd.DataFrame(final_dataset)
df.to_csv(OUTPUT_FILENAME, index=False)
print(f"\n🎉 FULLY COMPLETE! Database now has {len(df)} total games in '{OUTPUT_FILENAME}'")

🚀 Starting the Incremental Time-Slice TTRPG Scraper (Clean Slate - Pre-Skip Edition)...
📦 Loaded 1403 existing games from CSV.
🎯 Total target remaining: 8597 games.

[PHASE 1] Harvesting Links with Pre-Skip Logic...

📅 --- Searching Year: 1982 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added: 17  | Pre-Skipped: 83  | 🎯 Year Total: 17/211
  -> Scraping Page 2 ... | Added: 99  | Pre-Skipped: 1   | 🎯 Year Total: 116/211
  -> Scraping Page 3 ... | Added: 54  | Pre-Skipped: 0   | 🎯 Year Total: 170/211
  -> Scraping Page 4 ... | 🚨 End of year reached.
     ☕ Year 1982 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 8427

📅 --- Searching Year: 1983 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added: 82  | Pre-Skipped: 18  | 🎯 Year Total: 82/211
  -> Scraping Page 2 ... | Added: 99  | Pre-Skipped: 1   | 🎯 Year Total: 181/211
  -> Scraping Page 3 ... | Added: 30  | Pre-Skipped: 0   | 🎯 Year Total: 211/211
  -> 🎯 Reached 211 limit for 1983. Moving on.
     ☕ Year 1983 complete. Cooldown for 11s...
     📊 Total links still needed for 10k: 8216

📅 --- Searching Year: 1984 | Target for this year: 211 ---
  -> Scraping Page 1 ... | Added: 85  | Pre-Skipped: 15  | 🎯 Year Total: 85/211
  -> Scraping Page 2 ... | Added: 100 | Pre-Skipped: 0   | 🎯 Year Total: 185/211
  -> Scraping Page 3 ... | Added: 26  | Pre-Skipped: 0   | 🎯 Year Total: 211/211
  -> 🎯 Reached 211 limit for 1984. Moving on.
     ☕ Year 1984 complete. Cooldown for 18s...
     📊 Total links still needed for 10k: 8005

📅 --- Searching Year: 1985 | Target for this year: 210 ---
  -> Scraping Page 1 ... | Added: 86  | Pre-Skipped: 14  | 🎯 Year Total: 86/210
  -> Scraping Page 2 ... | Added: 98  | Pre-Skipped: 2   | 🎯 Year Total: 184/210
  -> Scraping Page 3 ... | Added: 26  | Pre-Skipped: 0   | 🎯 Year Total: 210/210
  -> 🎯 Reached 210 limit for 1985. Moving on.
     ☕ Year 1985 complete. Cooldown for 13s...
     📊 Total links still needed for 10k: 7795

📅 --- Searching Year: 1986 | Target for this year: 210 ---
  -> Scraping Page 1 ... | Added: 86  | Pre-Skipped: 13  | 🎯 Year Total: 86/210
  -> Scraping Page 2 ... | Added: 100 | Pre-Skipped: 0   | 🎯 Year Total: 186/210
  -> Scraping Page 3 ... | Added: 24  | Pre-Skipped: 0   | 🎯 Year Total: 210/210
  -> 🎯 Reached 210 limit for 1986. Moving on.
     ☕ Year 1986 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 7585

📅 --- Searching Year: 1987 | Target for this year: 209 ---
  -> Scraping Page 1 ... | Added: 81  | Pre-Skipped: 18  | 🎯 Year Total: 81/209
  -> Scraping Page 2 ... | Added: 99  | Pre-Skipped: 1   | 🎯 Year Total: 180/209
  -> Scraping Page 3 ... | Added: 29  | Pre-Skipped: 1   | 🎯 Year Total: 209/209
  -> 🎯 Reached 209 limit for 1987. Moving on.
     ☕ Year 1987 complete. Cooldown for 17s...
     📊 Total links still needed for 10k: 7376

KeyboardInterrupt:

In [1]:
import os
import time
import random
import re
import json
import html
import math
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

print("🚀 Starting the Year-by-Year Interleaved TTRPG Scraper (10-Scrape Auto-Save)...")

# --- SETUP ---
OUTPUT_FILENAME = "ttrpg_database_final.csv"
START_YEAR = 1985  # Updated to start at 1985
END_YEAR = 2026
TARGET_TOTAL_GAMES = 10000

scraper = cloudscraper.create_scraper(
    browser={'browser': 'chrome', 'platform': 'windows', 'desktop': True}
)

human_headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://boardgamegeek.com/advsearch/rpgitem",
    "Sec-Ch-Ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"Windows"',
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Upgrade-Insecure-Requests": "1"
}

# ==========================================
# PRE-FLIGHT: LOAD EXISTING DATA
# ==========================================
existing_names = set()
normalized_existing_names = set() 
final_dataset = []
seen_hrefs = set() # Global tracker to prevent cross-year duplicate URLs
session_scrapes_count = 0 # Tracks successful Phase 2 scrapes for our 10-save trigger

if os.path.exists(OUTPUT_FILENAME):
    try:
        existing_df = pd.read_csv(OUTPUT_FILENAME)
        existing_names = set(existing_df['Name'].str.lower().dropna())
        
        normalized_existing_names = set(
            re.sub(r'[^a-z0-9]', '', str(name).lower()) for name in existing_names
        )
        
        final_dataset = existing_df.to_dict('records') 
        print(f"📦 Loaded {len(final_dataset)} existing games from CSV.")
    except Exception as e:
        print(f"⚠️ Could not load existing dataset: {e}")
else:
    print("⚠️ No existing CSV found. Starting fresh.")


# ==========================================
# MAIN LOOP: YEAR-BY-YEAR INTERLEAVED SCRAPING
# ==========================================
years_list = list(range(START_YEAR, END_YEAR + 1))

for i, year in enumerate(years_list):
    
    # 1. Calculate precise deficit based on actual saved games
    target_needed = TARGET_TOTAL_GAMES - len(final_dataset)
    
    if target_needed <= 0:
        print(f"\n🏁 TARGET REACHED! We have exactly {TARGET_TOTAL_GAMES} games in the dataset.")
        break

    remaining_years = len(years_list) - i
    current_year_quota = math.ceil((target_needed / remaining_years) * 1.10) 
    
    print(f"\n=======================================================")
    print(f"📅 STARTING YEAR: {year} | Target needed to hit 10k: {target_needed}")
    print(f"=======================================================")
    
    # ---------------------------------------------------------
    # PHASE 1: HARVEST LINKS FOR THIS YEAR ONLY
    # ---------------------------------------------------------
    year_links = [] 
    year_links_collected = 0
    print(f"  [PHASE 1] Harvesting Max {current_year_quota} Links (Pre-Skipping Duplicates)...")
    
    for page in range(1, 11): 
        if year_links_collected >= current_year_quota:
            print(f"    -> 🎯 Reached {current_year_quota} limit for {year}.")
            break

        if page == 1:
            search_url = f"https://boardgamegeek.com/search/rpgitem?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        else:
            search_url = f"https://boardgamegeek.com/search/rpgitem/page/{page}?advsearch=1&range[yearpublished][min]={year}&range[yearpublished][max]={year}"
        
        print(f"    -> Scraping Page {page:<2}...", end=" ")
        
        try:
            res = scraper.get(search_url, headers=human_headers)
            time.sleep(random.uniform(4.0, 7.0)) 
            
            if res.status_code == 200:
                soup = BeautifulSoup(res.content, 'html.parser')
                raw_links = soup.find_all('a', href=re.compile(r'^/rpgitem/\d+/'))
                
                if not raw_links:
                    print("| 🚨 End of pages for this year.")
                    break 
                
                previous_unique_count = len(seen_hrefs)
                unique_page_links = set([link['href'] for link in raw_links])
                
                added_this_page = 0
                skipped_this_page = 0
                
                for href in unique_page_links:
                    if year_links_collected >= current_year_quota:
                        break

                    if href not in seen_hrefs:
                        url_rough_name = re.sub(r'[^a-z0-9]', '', href.split('/')[-1].lower())
                        
                        if url_rough_name in normalized_existing_names:
                            seen_hrefs.add(href)
                            skipped_this_page += 1
                            continue 
                        
                        seen_hrefs.add(href)
                        year_links.append((href, year)) 
                        year_links_collected += 1
                        added_this_page += 1
                
                print(f"| Added: {added_this_page:<3} | Pre-Skipped: {skipped_this_page:<3} | 🎯 Year Total: {year_links_collected}/{current_year_quota}")
                
                if len(seen_hrefs) == previous_unique_count:
                    print("       ⏭️ BGG is repeating pages. Breaking pagination loop.")
                    break 
                
            elif res.status_code == 403:
                print("| 🚨 403 Blocked! Cloudflare caught us.")
                break 
            else:
                print(f"| ⚠️ Failed. Status: {res.status_code}")
                break
                
        except Exception as e:
            print(f"| Error: {e}")

    # ---------------------------------------------------------
    # PHASE 2: SCRAPE DETAILS FOR THIS YEAR ONLY
    # ---------------------------------------------------------
    if not year_links:
        print(f"  [PHASE 2] No new links found for {year}. Skipping to next year.")
        continue

    print(f"\n  [PHASE 2] Scraping Details for {len(year_links)} new games from {year}...")
    
    for index, (link, game_year) in enumerate(year_links):
        if len(final_dataset) >= TARGET_TOTAL_GAMES:
            print(f"\n🏁 TARGET REACHED DURING PHASE 2! Halting.")
            break

        full_url = "https://boardgamegeek.com" + link
        search_name = link.split('/')[-1].replace('-', ' ').title() 
        
        print(f"    -> {index + 1}/{len(year_links)}: [{game_year}] {search_name[:15]:<15}...", end=" ")
        
        if search_name.lower() in existing_names:
            print("| ⏭️ Skipped (Already in CSV - Caught in Phase 2)")
            continue
        
        try:
            res = scraper.get(full_url)
            time.sleep(random.uniform(2.5, 4.0)) 
            
            if res.status_code == 200:
                soup = BeautifulSoup(res.content, 'html.parser')
                
                desc = "No description"
                meta_desc = soup.find('meta', attrs={'name': 'description'})
                if meta_desc:
                    desc = meta_desc['content']
                    desc = html.unescape(desc)
                    desc = re.sub(r"^\s*(From the publisher:|User summary:)\s*", "", desc, flags=re.IGNORECASE)
                    desc = re.sub(r'\n+', ' ', desc)
                    desc = re.sub(r'\s{2,}', ' ', desc).strip()
                    
                avg_score = 0.0
                num_reviews = 0
                
                scripts = soup.find_all('script')
                for script in scripts:
                    if script.string and 'GEEK.geekitemPreload' in script.string:
                        json_match = re.search(r'GEEK\.geekitemPreload\s*=\s*(\{.*?\});', script.string, re.DOTALL)
                        if json_match:
                            try:
                                data = json.loads(json_match.group(1))
                                stats = data.get('item', {}).get('stats', {})
                                avg_score = float(stats.get('average', 0.0))
                                num_reviews = int(stats.get('usersrated', 0))
                                
                                official_name = data.get('item', {}).get('name')
                                if official_name:
                                    search_name = official_name
                            except json.JSONDecodeError:
                                pass
                        break 
                        
                final_dataset.append({
                    'Name': search_name,
                    'Publishing Year': game_year,
                    'Description': desc,
                    'Average Score': avg_score,
                    'Number of Reviews': num_reviews
                })
                
                # Immediately update both tracking sets so Phase 1 knows about it next year
                existing_names.add(search_name.lower())
                normalized_existing_names.add(re.sub(r'[^a-z0-9]', '', search_name.lower()))
                
                print(f"| ✅ Score: {avg_score:.2f} | Total DB: {len(final_dataset)}")
                
                # 🌟 THE 10-SCRAPE AUTO-SAVE 🌟
                session_scrapes_count += 1
                if session_scrapes_count % 10 == 0:
                    pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
                    print(f"       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.")
                
            elif res.status_code == 429:
                print("| 🚨 Rate Limited! Pausing for 30 seconds...")
                time.sleep(30)
            elif res.status_code == 403:
                print("| 🚨 403 Forbidden! Cloudflare blocked you.")
                time.sleep(30)
            else:
                print(f"| ⚠️ Failed Status: {res.status_code}")
                
        except Exception as e:
            print(f"| Error: {e}")

    # --- END OF YEAR CHECKPOINT ---
    pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
    
    cooldown = random.randint(15, 30)
    print(f"\n  💾 Checkpoint: {year} Complete & Saved. Total DB: {len(final_dataset)}")
    print(f"  ☕ Inter-year cooldown for {cooldown}s...")
    time.sleep(cooldown)

# ==========================================
# FINAL WRAP UP
# ==========================================
# One final save just in case the loop breaks before a multiple of 10 or end of year
pd.DataFrame(final_dataset).to_csv(OUTPUT_FILENAME, index=False)
print(f"\n🎉 SCRIPT FINISHED! Database now has {len(final_dataset)} total games in '{OUTPUT_FILENAME}'")

🚀 Starting the Year-by-Year Interleaved TTRPG Scraper (10-Scrape Auto-Save)...
📦 Loaded 1995 existing games from CSV.

=======================================================
📅 STARTING YEAR: 1985 | Target needed to hit 10k: 8005
=======================================================
  [PHASE 1] Harvesting Max 210 Links (Pre-Skipping Duplicates)...
    -> Scraping Page 1 ... | Added: 86  | Pre-Skipped: 14  | 🎯 Year Total: 86/210
    -> Scraping Page 2 ... | Added: 98  | Pre-Skipped: 2   | 🎯 Year Total: 184/210
    -> Scraping Page 3 ... | Added: 26  | Pre-Skipped: 0   | 🎯 Year Total: 210/210
    -> 🎯 Reached 210 limit for 1985.

  [PHASE 2] Scraping Details for 210 new games from 1985...
    -> 1/210: [1985] Gods Of Harn   ... | ✅ Score: 8.12 | Total DB: 1996
    -> 2/210: [1985] Stormbringer 2N... | ✅ Score: 7.00 | Total DB: 1997
    -> 3/210: [1985] Mystery Of The ... | ✅ Score: 5.27 | Total DB: 1998
    -> 4/210: [1985] Dragons Of War ... | ✅ Score: 6.47 | Total DB: 1999
    -> 5/210: [1985] Judge Dredd The... | ✅ Score: 6.89 | Total DB: 2000
    -> 6/210: [1985] The Kingdoms Of... | ✅ Score: 7.40 | Total DB: 2001
    -> 7/210: [1985] Droyne         ... | ✅ Score: 7.27 | Total DB: 2002
    -> 8/210: [1985] Skyrealms Of Jo... | ✅ Score: 6.65 | Total DB: 2003
    -> 9/210: [1985] Conan The Bucca... | ✅ Score: 5.70 | Total DB: 2004
    -> 10/210: [1985] The Lexicon Atl... | ✅ Score: 7.17 | Total DB: 2005
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 11/210: [1985] Drakar Och Demo... | ✅ Score: 7.79 | Total DB: 2006
    -> 12/210: [1985] Castle Caldwell... | ✅ Score: 6.11 | Total DB: 2007
    -> 13/210: [1985] Swords Of The U... | ✅ Score: 7.15 | Total DB: 2008
    -> 14/210: [1985] The Bane Of Lly... | ✅ Score: 6.63 | Total DB: 2009
    -> 15/210: [1985] Alone Against T... | ✅ Score: 7.22 | Total DB: 2010
    -> 16/210: [1985] Isle Of The Ape... | ✅ Score: 6.07 | Total DB: 2011
    -> 17/210: [1985] Alone Against T... | ✅ Score: 6.54 | Total DB: 2012
    -> 18/210: [1985] Avenger        ... | ✅ Score: 7.60 | Total DB: 2013
    -> 19/210: [1985] Zebulons Guide ... | ✅ Score: 7.46 | Total DB: 2014
    -> 20/210: [1985] Teenage Mutant ... | ✅ Score: 6.68 | Total DB: 2015
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 21/210: [1985] Goldfinger Ii T... | ✅ Score: 5.80 | Total DB: 2016
    -> 22/210: [1985] Creatures And T... | ✅ Score: 7.27 | Total DB: 2017
    -> 23/210: [1985] Appointment Wit... | ✅ Score: 6.98 | Total DB: 2018
    -> 24/210: [1985] Goblin Gate And... | ✅ Score: 6.91 | Total DB: 2019
    -> 25/210: [1985] Dragons Of Drea... | ✅ Score: 6.47 | Total DB: 2020
    -> 26/210: [1985] Conan Role Play... | ✅ Score: 6.67 | Total DB: 2021
    -> 27/210: [1985] The Book Of Mar... | ✅ Score: 6.40 | Total DB: 2022
    -> 28/210: [1985] To Find A King ... | ✅ Score: 6.95 | Total DB: 2023
    -> 29/210: [1985] Dragonroar     ... | ✅ Score: 4.50 | Total DB: 2024
    -> 30/210: [1985] Dragons Of Ice ... | ✅ Score: 6.07 | Total DB: 2025
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 31/210: [1985] Night Of The Na... | ✅ Score: 7.92 | Total DB: 2026
    -> 32/210: [1985] Red Arrow Black... | ✅ Score: 7.22 | Total DB: 2027
    -> 33/210: [1985] Nightmare In No... | ✅ Score: 5.56 | Total DB: 2028
    -> 34/210: [1985] Master Player S... | ✅ Score: 6.29 | Total DB: 2029
    -> 35/210: [1985] Temple Of Terro... | ✅ Score: 6.59 | Total DB: 2030
    -> 36/210: [1985] The Black Madon... | ✅ Score: 7.72 | Total DB: 2031
    -> 37/210: [1985] Grey Star The W... | ✅ Score: 7.45 | Total DB: 2032
    -> 38/210: [1985] Danger Internat... | ✅ Score: 6.93 | Total DB: 2033
    -> 39/210: [1985] Baltrons Beacon... | ✅ Score: 7.21 | Total DB: 2034
    -> 40/210: [1985] Evenings Of Ter... | ✅ Score: 7.70 | Total DB: 2035
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 41/210: [1985] Doctor Who Role... | ✅ Score: 6.29 | Total DB: 2036
    -> 42/210: [1985] Romulan Ship Re... | ✅ Score: 7.53 | Total DB: 2037
    -> 43/210: [1985] Earthshaker    ... | ✅ Score: 5.82 | Total DB: 2038
    -> 44/210: [1985] Riders Of Rohan... | ✅ Score: 7.28 | Total DB: 2039
    -> 45/210: [1985] Where Chaos Rei... | ✅ Score: 6.07 | Total DB: 2040
    -> 46/210: [1985] Dc Heroes Role ... | ✅ Score: 7.06 | Total DB: 2041
    -> 47/210: [1985] The Free City O... | ✅ Score: 7.42 | Total DB: 2042
    -> 48/210: [1985] Dinky Dungeons ... | ✅ Score: 6.25 | Total DB: 2043
    -> 49/210: [1985] Lankhmar City O... | ✅ Score: 7.20 | Total DB: 2044
    -> 50/210: [1985] Dragons Of Dece... | ✅ Score: 6.41 | Total DB: 2045
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 51/210: [1985] Black Sword    ... | ✅ Score: 6.33 | Total DB: 2046
    -> 52/210: [1985] Pirates Of The ... | ✅ Score: 7.22 | Total DB: 2047
    -> 53/210: [1985] Thieves Of Thar... | ✅ Score: 7.08 | Total DB: 2048
    -> 54/210: [1985] The Way Of Wiza... | ✅ Score: 7.94 | Total DB: 2049
    -> 55/210: [1985] The Elven Cryst... | ✅ Score: 7.42 | Total DB: 2050
    -> 56/210: [1985] Perilous Lands ... | ✅ Score: 6.39 | Total DB: 2051
    -> 57/210: [1985] Freeway Fighter... | ✅ Score: 6.48 | Total DB: 2052
    -> 58/210: [1985] The Legend Of W... | ✅ Score: 8.39 | Total DB: 2053
    -> 59/210: [1985] Thunderdelve Mo... | ✅ Score: 5.90 | Total DB: 2054
    -> 60/210: [1985] Vikings Nordic ... | ✅ Score: 7.33 | Total DB: 2055
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 61/210: [1985] Haunted Ruins O... | ✅ Score: 7.02 | Total DB: 2056
    -> 62/210: [1985] Thrilling Locat... | ✅ Score: 7.12 | Total DB: 2057
    -> 63/210: [1985] Bloodstone Pass... | ✅ Score: 6.67 | Total DB: 2058
    -> 64/210: [1985] The Chasm Of Do... | ✅ Score: 7.31 | Total DB: 2059
    -> 65/210: [1985] Legacy Of Eagle... | ✅ Score: 7.60 | Total DB: 2060
    -> 66/210: [1985] The Mechanoids ... | ✅ Score: 6.33 | Total DB: 2061
    -> 67/210: [1985] 3 D Dragon Tile... | ✅ Score: 6.38 | Total DB: 2062
    -> 68/210: [1985] The Lost Shrine... | ✅ Score: 6.00 | Total DB: 2063
    -> 69/210: [1985] Paranoia Gamema... | ✅ Score: 6.97 | Total DB: 2064
    -> 70/210: [1985] Dungeons And Dr... | ✅ Score: 7.08 | Total DB: 2065
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 71/210: [1985] Sandman Map Of ... | ✅ Score: 7.53 | Total DB: 2066
    -> 72/210: [1985] The Blood And D... | ✅ Score: 7.33 | Total DB: 2067
    -> 73/210: [1985] Into The Maelst... | ✅ Score: 6.46 | Total DB: 2068
    -> 74/210: [1985] Battlesystem Fa... | ✅ Score: 5.71 | Total DB: 2069
    -> 75/210: [1985] Man To Man     ... | ✅ Score: 6.21 | Total DB: 2070
    -> 76/210: [1985] Midnight At The... | ✅ Score: 3.00 | Total DB: 2071
    -> 77/210: [1985] Demon Magic The... | ✅ Score: 6.10 | Total DB: 2072
    -> 78/210: [1985] Behind Enemy Li... | ✅ Score: 7.30 | Total DB: 2073
    -> 79/210: [1985] Character Law A... | ✅ Score: 6.91 | Total DB: 2074
    -> 80/210: [1985] Ivinia The Viki... | ✅ Score: 7.55 | Total DB: 2075
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 81/210: [1985] The Golden Age ... | ✅ Score: 7.43 | Total DB: 2076
    -> 82/210: [1985] The Castle Of L... | ✅ Score: 6.92 | Total DB: 2077
    -> 83/210: [1985] Queen Victoria ... | ✅ Score: 6.71 | Total DB: 2078
    -> 84/210: [1985] Fantasy Hero 3R... | ✅ Score: 6.81 | Total DB: 2079
    -> 85/210: [1985] Rangers Of The ... | ✅ Score: 7.26 | Total DB: 2080
    -> 86/210: [1985] The Savage Coas... | ✅ Score: 5.50 | Total DB: 2081
    -> 87/210: [1985] Here There Be T... | ✅ Score: 9.00 | Total DB: 2082
    -> 88/210: [1985] You Can Be The ... | ✅ Score: 2.33 | Total DB: 2083
    -> 89/210: [1985] Conan Triumphan... | ✅ Score: 9.00 | Total DB: 2084
    -> 90/210: [1985] Bugs In The Sys... | ✅ Score: 6.46 | Total DB: 2085
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 91/210: [1985] Havena         ... | ✅ Score: 6.18 | Total DB: 2086
    -> 92/210: [1985] Nepal Nightmare... | ✅ Score: 6.78 | Total DB: 2087
    -> 93/210: [1985] Assassin       ... | ✅ Score: 7.67 | Total DB: 2088
    -> 94/210: [1985] The Cardinals P... | ✅ Score: 7.96 | Total DB: 2089
    -> 95/210: [1985] Send In The Clo... | ✅ Score: 7.71 | Total DB: 2090
    -> 96/210: [1985] Abenteuer Ausba... | ✅ Score: 6.70 | Total DB: 2091
    -> 97/210: [1985] Klingon Ship Re... | ✅ Score: 7.62 | Total DB: 2092
    -> 98/210: [1985] Assassin       ... | ⏭️ Skipped (Already in CSV - Caught in Phase 2)
    -> 99/210: [1985] Future Law     ... | ✅ Score: 5.55 | Total DB: 2093
    -> 100/210: [1985] The Soulforge  ... | ✅ Score: 6.94 | Total DB: 2094
    -> 101/210: [1985] Midgard Das Fan... | ✅ Score: 7.50 | Total DB: 2095
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 102/210: [1985] Monsters And An... | ✅ Score: 6.50 | Total DB: 2096
    -> 103/210: [1985] Malefices      ... | ✅ Score: 9.33 | Total DB: 2097
    -> 104/210: [1985] Federation Ship... | ✅ Score: 7.97 | Total DB: 2098
    -> 105/210: [1985] Hunter Planet  ... | ✅ Score: 8.00 | Total DB: 2099
    -> 106/210: [1985] Tower Of Midnig... | ✅ Score: 0.00 | Total DB: 2100
    -> 107/210: [1985] An Ambassadors ... | ✅ Score: 8.25 | Total DB: 2101
    -> 108/210: [1985] Zhodani        ... | ✅ Score: 7.67 | Total DB: 2102
    -> 109/210: [1985] Usurper        ... | ✅ Score: 7.17 | Total DB: 2103
    -> 110/210: [1985] Das Schwarze Au... | ✅ Score: 6.27 | Total DB: 2104
    -> 111/210: [1985] The Rings Of Ke... | ✅ Score: 6.53 | Total DB: 2105
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 112/210: [1985] The Triangle   ... | ✅ Score: 7.84 | Total DB: 2106
    -> 113/210: [1985] Rebel Planet   ... | ✅ Score: 5.99 | Total DB: 2107
    -> 114/210: [1985] Toon Silly Stuf... | ✅ Score: 6.75 | Total DB: 2108
    -> 115/210: [1985] Fragments Of Fe... | ✅ Score: 6.11 | Total DB: 2109
    -> 116/210: [1985] New York New Yo... | ✅ Score: 7.06 | Total DB: 2110
    -> 117/210: [1985] Vapors Dont Sho... | ✅ Score: 7.12 | Total DB: 2111
    -> 118/210: [1985] The Golden Godd... | ✅ Score: 6.12 | Total DB: 2112
    -> 119/210: [1985] Challenge Of Dr... | ✅ Score: 5.00 | Total DB: 2113
    -> 120/210: [1985] Vikings And Val... | ✅ Score: 0.00 | Total DB: 2114
    -> 121/210: [1985] The Master     ... | ✅ Score: 7.00 | Total DB: 2115
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 122/210: [1985] Escape From Cas... | ✅ Score: 6.75 | Total DB: 2116
    -> 123/210: [1985] The Elfquest Co... | ✅ Score: 6.75 | Total DB: 2117
    -> 124/210: [1985] Seas Of Blood  ... | ✅ Score: 6.88 | Total DB: 2118
    -> 125/210: [1985] The Iytean Mena... | ✅ Score: 7.08 | Total DB: 2119
    -> 126/210: [1985] Prisoners Of Pa... | ✅ Score: 5.90 | Total DB: 2120
    -> 127/210: [1985] Monster Coliseu... | ✅ Score: 5.00 | Total DB: 2121
    -> 128/210: [1985] Curse Of The Ph... | ✅ Score: 5.33 | Total DB: 2122
    -> 129/210: [1985] Deathwatch On T... | ✅ Score: 7.50 | Total DB: 2123
    -> 130/210: [1985] The Future King... | ✅ Score: 0.00 | Total DB: 2124
    -> 131/210: [1985] The Masters Of ... | ✅ Score: 1.00 | Total DB: 2125
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 132/210: [1985] Dwarven Halls  ... | ✅ Score: 7.40 | Total DB: 2126
    -> 133/210: [1985] The Ruins Of Wa... | ✅ Score: 6.64 | Total DB: 2127
    -> 134/210: [1985] Graduation Exer... | ✅ Score: 7.33 | Total DB: 2128
    -> 135/210: [1985] The Eye Of The ... | ✅ Score: 8.00 | Total DB: 2129
    -> 136/210: [1985] Kingdom Of Horr... | ✅ Score: 7.06 | Total DB: 2130
    -> 137/210: [1985] The Web Of Elda... | ✅ Score: 6.67 | Total DB: 2131
    -> 138/210: [1985] Dark Clouds Gat... | ✅ Score: 7.15 | Total DB: 2132
    -> 139/210: [1985] Erech And The P... | ✅ Score: 6.29 | Total DB: 2133
    -> 140/210: [1985] Face Of The Ene... | ✅ Score: 5.50 | Total DB: 2134
    -> 141/210: [1985] Voyage Of Terro... | ✅ Score: 7.11 | Total DB: 2135
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 142/210: [1985] Clockwork Mage ... | ✅ Score: 6.00 | Total DB: 2136
    -> 143/210: [1985] Bloodfeud Of Al... | ✅ Score: 7.21 | Total DB: 2137
    -> 144/210: [1985] Falcon 2 Mechan... | ✅ Score: 0.00 | Total DB: 2138
    -> 145/210: [1985] Das Schwarze Au... | ✅ Score: 6.95 | Total DB: 2139
    -> 146/210: [1985] Orcslayer      ... | ✅ Score: 6.25 | Total DB: 2140
    -> 147/210: [1985] The Spinward Ma... | ✅ Score: 7.50 | Total DB: 2141
    -> 148/210: [1985] Castle Thrax   ... | ✅ Score: 0.00 | Total DB: 2142
    -> 149/210: [1985] First Quest The... | ✅ Score: 4.00 | Total DB: 2143
    -> 150/210: [1985] Judges Survival... | ✅ Score: 7.77 | Total DB: 2144
    -> 151/210: [1985] Where Has All T... | ✅ Score: 6.86 | Total DB: 2145
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 152/210: [1985] The War Machine... | ✅ Score: 7.00 | Total DB: 2146
    -> 153/210: [1985] Warlords       ... | ✅ Score: 0.00 | Total DB: 2147
    -> 154/210: [1985] Dark Side Of Th... | ✅ Score: 5.88 | Total DB: 2148
    -> 155/210: [1985] The Ghost Tower... | ✅ Score: 6.83 | Total DB: 2149
    -> 156/210: [1985] At The Court Of... | ✅ Score: 7.60 | Total DB: 2150
    -> 157/210: [1985] Signal Gk      ... | ✅ Score: 7.57 | Total DB: 2151
    -> 158/210: [1985] Space Master 1S... | ✅ Score: 5.81 | Total DB: 2152
    -> 159/210: [1985] Top Secret Comp... | ✅ Score: 6.25 | Total DB: 2153
    -> 160/210: [1985] The Daleks     ... | ✅ Score: 6.86 | Total DB: 2154
    -> 161/210: [1985] Concrete Jungle... | ✅ Score: 6.08 | Total DB: 2155
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 162/210: [1985] Das Schwarze Au... | ✅ Score: 6.42 | Total DB: 2156
    -> 163/210: [1985] Drakar Och Demo... | ✅ Score: 7.15 | Total DB: 2157
    -> 164/210: [1985] The Fourth Nail... | ✅ Score: 6.67 | Total DB: 2158
    -> 165/210: [1985] Toon Strikes Ag... | ✅ Score: 7.25 | Total DB: 2159
    -> 166/210: [1985] Freaks And Frie... | ✅ Score: 5.00 | Total DB: 2160
    -> 167/210: [1985] Falcon 1 The Re... | ✅ Score: 0.00 | Total DB: 2161
    -> 168/210: [1985] Dragons Of Ligh... | ✅ Score: 6.41 | Total DB: 2162
    -> 169/210: [1985] Castle Arcania ... | ✅ Score: 5.00 | Total DB: 2163
    -> 170/210: [1985] A View To A Kil... | ✅ Score: 6.67 | Total DB: 2164
    -> 171/210: [1985] Action On Akais... | ✅ Score: 5.83 | Total DB: 2165
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 172/210: [1985] The Justice Mac... | ✅ Score: 5.27 | Total DB: 2166
    -> 173/210: [1985] Falcon 3 The Ra... | ✅ Score: 7.00 | Total DB: 2167
    -> 174/210: [1985] Trail Of The Lo... | ✅ Score: 5.00 | Total DB: 2168
    -> 175/210: [1985] The Man With Th... | ✅ Score: 7.43 | Total DB: 2169
    -> 176/210: [1985] Das Geheimnis D... | ✅ Score: 6.46 | Total DB: 2170
    -> 177/210: [1985] The Hartlewick ... | ✅ Score: 6.67 | Total DB: 2171
    -> 178/210: [1985] Timetricks A Su... | ✅ Score: 8.07 | Total DB: 2172
    -> 179/210: [1985] Conan The Merce... | ✅ Score: 7.25 | Total DB: 2173
    -> 180/210: [1985] Lythia         ... | ✅ Score: 8.00 | Total DB: 2174
    -> 181/210: [1985] Revenge Of The ... | ✅ Score: 7.00 | Total DB: 2175
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 182/210: [1985] Space Assassin ... | ✅ Score: 6.73 | Total DB: 2176
    -> 183/210: [1985] The Sea Elves  ... | ✅ Score: 6.50 | Total DB: 2177
    -> 184/210: [1985] Adventurer Shee... | ✅ Score: 4.50 | Total DB: 2178
    -> 185/210: [1985] Street Fighter ... | ✅ Score: 7.40 | Total DB: 2179
    -> 186/210: [1985] The Maze And Th... | ✅ Score: 6.00 | Total DB: 2180
    -> 187/210: [1985] Siege          ... | ✅ Score: 6.67 | Total DB: 2181
    -> 188/210: [1985] Ice Elves      ... | ✅ Score: 0.00 | Total DB: 2182
    -> 189/210: [1985] Elven Banner   ... | ✅ Score: 6.50 | Total DB: 2183
    -> 190/210: [1985] Tales Of The Bl... | ✅ Score: 6.60 | Total DB: 2184
    -> 191/210: [1985] The Witchs Spel... | ✅ Score: 0.00 | Total DB: 2185
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 192/210: [1985] James Bond In P... | ✅ Score: 0.00 | Total DB: 2186
    -> 193/210: [1985] Nekropolis     ... | ✅ Score: 6.20 | Total DB: 2187
    -> 194/210: [1985] The Triangle Ca... | ✅ Score: 8.10 | Total DB: 2188
    -> 195/210: [1985] Tarzan And The ... | ✅ Score: 0.00 | Total DB: 2189
    -> 196/210: [1985] Battle For The ... | ✅ Score: 6.00 | Total DB: 2190
    -> 197/210: [1985] The Fireseed   ... | ✅ Score: 7.00 | Total DB: 2191
    -> 198/210: [1985] World Action An... | ✅ Score: 5.00 | Total DB: 2192
    -> 199/210: [1985] The Black Pyram... | ✅ Score: 5.67 | Total DB: 2193
    -> 200/210: [1985] Monsters Of The... | ✅ Score: 6.00 | Total DB: 2194
    -> 201/210: [1985] The Mystery Of ... | ✅ Score: 6.00 | Total DB: 2195
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 202/210: [1985] The Outcasts   ... | ✅ Score: 7.80 | Total DB: 2196
    -> 203/210: [1985] Terror At Sea  ... | ✅ Score: 7.42 | Total DB: 2197
    -> 204/210: [1985] Blood Feud     ... | ✅ Score: 6.50 | Total DB: 2198
    -> 205/210: [1985] High Seas      ... | ✅ Score: 8.25 | Total DB: 2199
    -> 206/210: [1985] James Bond In W... | ✅ Score: 6.00 | Total DB: 2200
    -> 207/210: [1985] The Mystery Of ... | ✅ Score: 5.00 | Total DB: 2201
    -> 208/210: [1985] Aliens         ... | ✅ Score: 7.50 | Total DB: 2202
    -> 209/210: [1985] Auf Dem Weg Ohn... | ✅ Score: 5.53 | Total DB: 2203
    -> 210/210: [1985] The Tome       ... | ✅ Score: 7.50 | Total DB: 2204

  💾 Checkpoint: 1985 Complete & Saved. Total DB: 2204
  ☕ Inter-year cooldown for 30s...

=======================================================
📅 STARTING YEAR: 1986 | Target needed to hit 10k: 7796
=======================================================
  [PHASE 1] Harvesting Max 210 Links (Pre-Skipping Duplicates)...
    -> Scraping Page 1 ... | Added: 85  | Pre-Skipped: 14  | 🎯 Year Total: 85/210
    -> Scraping Page 2 ... | Added: 99  | Pre-Skipped: 1   | 🎯 Year Total: 184/210
    -> Scraping Page 3 ... | Added: 26  | Pre-Skipped: 0   | 🎯 Year Total: 210/210
    -> 🎯 Reached 210 limit for 1986.

  [PHASE 2] Scraping Details for 210 new games from 1986...
    -> 1/210: [1986] Wilderness Surv... | ✅ Score: 6.22 | Total DB: 2205
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 2/210: [1986] The Book Of Lai... | ✅ Score: 6.97 | Total DB: 2206
    -> 3/210: [1986] The Octagon Of ... | ✅ Score: 7.00 | Total DB: 2207
    -> 4/210: [1986] Destiny Of King... | ✅ Score: 7.62 | Total DB: 2208
    -> 5/210: [1986] H P Lovecrafts ... | ✅ Score: 7.46 | Total DB: 2209
    -> 6/210: [1986] Treasure Hunt  ... | ✅ Score: 6.98 | Total DB: 2210
    -> 7/210: [1986] Demons Of The D... | ✅ Score: 7.00 | Total DB: 2211
    -> 8/210: [1986] The Statue Of T... | ✅ Score: 6.61 | Total DB: 2212
    -> 9/210: [1986] Adventures In B... | ✅ Score: 6.18 | Total DB: 2213
    -> 10/210: [1986] Star Trek The R... | ✅ Score: 7.72 | Total DB: 2214
    -> 11/210: [1986] The Feathered P... | ✅ Score: 7.25 | Total DB: 2215
       💾 Auto-Save: 10 new games acquired. CSV safely overwritten.
    -> 12/210: [1986] The Immortal St... | ✅ Score: 5.27 | Total DB: 2216
    -> 13/210: [1986] Year Of The Pho... | ✅ Score: 6.00 | Total DB: 2217
    -> 14/210: [1986] Rescue In Mirkw... | ✅ Score: 7.71 | Total DB: 2218
    -> 15/210: [1986] Red Sonja Uncon... | ✅ Score: 6.11 | Total DB: 2219
    -> 16/210: [1986] Dragons Of Triu... | ✅ Score: 6.17 | Total DB: 2220
    -> 17/210: [1986] Robotech The Ro... | ✅ Score: 6.00 | Total DB: 2221
    -> 18/210: [1986] The Tree Of Lif... | ✅ Score: 6.18 | Total DB: 2222
    -> 19/210: [1986] Robot Warriors ... | ✅ Score: 5.91 | Total DB: 2223
    -> 20/210: [1986] Mechwarrior    ... | ✅ Score: 6.00 | Total DB: 2224

KeyboardInterrupt: